### ISSUE TITLE
State vector differences between poliastro.twobody.Orbit and spg4

### ISSUE THREAD

**Issue by jtegedor** [poliastro/poliastro#1185] opened 2021-04-29 10:40 UTC
I am trying to compare various `poliastro` orbit propagation methods vs the `spg4` propagator. However, the resulting state vectors are significantly different between both.

🐞 **Problem**

Essentially, we generate a `poliastro.twobody.Orbit` and use it to initialise the `spg4` orbit. However, when converting back from `spg4` to `Orbit` (for the same epoch, without actual propagation), the state vector is off by several kilometres.

Sample code here:

```
#!/usr/local/bin/python3

from astropy import coordinates as coord, units as u
from astropy.time import Time
from astropy.coordinates import TEME

from poliastro.twobody import Orbit
from poliastro.bodies import Earth
from poliastro.twobody import angles
from poliastro.examples import iss

from sgp4.api import Satrec, SGP4_ERRORS, WGS84


if __name__ == "__main__":

    # Display some initial data
    print(f" Orbit: {iss}")
    print(" State vector [poliastro]")
    print(f"     r = {iss.r}")
    print(f"     v = {iss.v}")
    print()

    # Generate the equivalent using spg4
    epochTime = Time(iss.epoch, format='datetime', scale='utc')
    eccAnomaly = angles.nu_to_E(iss.nu, iss.ecc)
    meanAnomaly = angles.E_to_M(eccAnomaly, iss.ecc)
    sat = Satrec()
    sat.sgp4init(WGS84, 'i', 0, epochTime.jd - 2433281.5, 0.0, 0.0, 0.0,
                 iss.ecc, iss.argp.value, iss.inc.value, meanAnomaly.value,
                 iss.n.to(u.rad/u.minute).value, iss.raan.value,
                 )

    # Compute state vector from sgp4
    errorCode, rTEME, vTEME = sat.sgp4(epochTime.jd1, epochTime.jd2)
    if errorCode != 0:
        raise RuntimeError(SGP4_ERRORS[errorCode])

    pTEME = coord.CartesianRepresentation(rTEME*u.km)
    vTEME = coord.CartesianDifferential(vTEME*u.km/u.s)
    svTEME = TEME(pTEME.with_differentials(vTEME), obstime=iss.epoch)

    svITRS = svTEME.transform_to(coord.ITRS(obstime=iss.epoch))
    sv = Orbit.from_coords(Earth, svITRS)
    print("State vector [spg4]")
    print(f"     r = {sv.r}")
    print(f"     v = {sv.v}")
    print()

    print("State vector differences [poliastro - spg4]")
    print(f"     r = {iss.r - sv.r}")
    print(f"     v = {iss.v - sv.v}")
    print()
```

🖥 Results:

```
 State vector [poliastro]
     r = [  859.07256 -4137.20368  5295.56871] km
     v = [7.37289205 2.08223573 0.43999979] km / s

State vector [spg4]
     r = [  852.72472797 -4137.51683084  5287.30166418] km
     v = [7.38429906 2.06186541 0.430843  ] km / s

State vector differences [poliastro - spg4]
     r = [6.34783203 0.31315084 8.26704582] km
     v = [-0.01140701  0.02037032  0.0091568 ] km / s
```
💡 **Possible solutions**

This involves a combination of `poliastro`, `astropy` and `spg4` and transformation between different frames, so it is not clear where the problem is.

Any advise is much appreciated.

**Comment by astrojuanlu** [comment] 2021-04-29 11:46
Hello @jtegedor, thanks again for your interest in poliastro!

> This involves a combination of poliastro, astropy and spg4 and transformation between different frames, so it is not clear where the problem is.

Yeah, exactly. We will have a look at this shortly.

**Comment by astrojuanlu** [comment] 2021-05-01 10:02
After giving this a closer inspection, I can conclude that this is "not a bug", but a very common confusion arising with TLEs. Let me explain without getting into much detail.

This line:

```python
    sat.sgp4init(WGS84, 'i', 0, epochTime.jd - 2433281.5, 0.0, 0.0, 0.0,
                 iss.ecc, iss.argp.value, iss.inc.value, meanAnomaly.value,
                 iss.n.to(u.rad/u.minute).value, iss.raan.value,
                 )
```

creates a TLE using _osculating_ orbital elements, which are the ones that `Orbit` objects in poliastro handle. As poliastro is mostly concerned with the purely Keplerian two body problem, this is everything we need.

However, as you know better than me<sup>1</sup>, the real world is way more complex, and orbits deviate from its purely Keplerian motion _all the time_. As a result, osculating elements only have value on a given instant in time, but they slowly evolve with time (with the exception, of course, of anomalies, that change rapidly anyway).

And here comes the common mistake: TLEs do _not_ use osculating elements, but **Brouwer _mean_ elements**. They are _mean_ elements because they use some averaging technique over a period of time, and this technique is due to Dirk Brouwer (Brouwer, Dirk "Solution of the Problem of Artificial Satellite Theory without Drag", 1959) as opposed to, say, Kozai mean elements (Kozai, Yoshihide "The Motion of a Close Earth Satellite", 1959).

In summary, when creating a TLE directly from osculating elements, this leads to a systematic error, and therefore one cannot expect the propagation to be accurate (they will be [_precise_, but not _accurate_](https://en.wikipedia.org/wiki/Accuracy_and_precision?oldformat=true#Common_technical_definition), i.e. close to the true value).

This is a surprisingly common misconception that is not clearly addressed in the famous [TLE FAQ by Dr. T. S. Kelso](http://celestrak.com/columns/v04n03/). I have pointed out this mistake in other places, for example in https://github.com/aerospaceresearch/orbitdeterminator/issues/195.

There are several ways to do this properly:

- This GPLv3 tool by @cbassa https://github.com/cbassa/twoline of the Scott Campbell algorithm http://sat.belastro.net/satelliteorbitdetermination.com/RV2EL.txt
- The original SGP4 Orbit Determination algorithm from a set of observations by Vallado & Crawford https://celestrak.com/publications/AIAA/2008-6770/ (notice that this is a slightly different problem)

And there are several actions we could take on the poliastro side:

- Add the wall-of-text above to the "Background" section of our documentation, with more examples and mathematical formulas, so it's more easily discoverable by our users.
- Work on better `poliastro.twobody.Orbit` to/from TLE (or [any other GP data format, like OMM](https://celestrak.com/NORAD/documentation/gp-data-formats.php)) so there is a clear API that does _the right thing_™ and reduces confusion. 

Please @jtegedor let me know if all of this makes sense.

<sup>Please forgive this "mansplaining" line - it's not for you @jtegedor, but for future readers!</sup>

**Comment by jtegedor** [comment] 2021-05-02 13:29
Hi @astrojuanlu , thanks for the feedback!

After a deeper look, it looks like `spg4init` is expecting mean orbital elements indeed, not the osculating ones from `poliastro`.

However, I had a look at [https://github.com/cbassa/twoline](https://github.com/cbassa/twoline), and looks to me that is it also computing osculating elements, actually the results are similar to those of `poliastro`, see stdout of 
[testPoliSPG4.py.gz](https://github.com/poliastro/poliastro/files/6411428/testPoliSPG4.py.gz):

```root@56e1c51e9d49:/workspaces/FSPy# bin/testPoliSPG4.py 
WARNING: AstropyDeprecationWarning: The private astropy._erfa module has been made into its own package, pyerfa, which is a dependency of astropy and can be imported directly using "import erfa" [astropy._erfa]
 Orbit: 6772 x 6790 km x 51.6 deg (GCRS) orbit around Earth (♁) at epoch 2013-03-18 12:00:00.000 (UTC)
 State vector [poliastro]
     r = [  859.07256 -4137.20368  5295.56871] km
     v = [7.37289205 2.08223573 0.43999979] km / s

                  Poliastro     twoline.rv2tle
Ecc            :    0.00131            0.00124
Incl  [deg]    :   51.60121           51.62100
n [deg/min]    :    3.88701            3.88237
RAAN  [deg]    :  198.37950          198.37580
Argp + M [deg] :   85.75009           85.74690

State vector [rv2tle->spg4]
     r = [  853.79087959 -4139.88041104  5294.34973779] km
     v = [7.37955298 2.06042969 0.43038546] km / s

State vector differences [poliastro - spg4]
    dr = [5.28168041 2.67673104 1.21897221] km
    dv = [-0.00666093  0.02180604  0.00961433] km / s
```

I think that the correct way to proceed here is to convert `r`/`v` to mean orbital elements, using the `rvel` routine from [RV2EL.txt](http://sat.belastro.net/satelliteorbitdetermination.com/RV2EL.txt).

Further comments/ideas very much welcome.

**Comment by jtegedor** [comment] 2021-05-05 17:36
Made some more progress on this topic.

After the proper conversion of state vector to mean orbital elements (see [rv2tle.py](https://github.com/jtegedor/rv2tle/blob/master/rv2tle.py)), using the algorithm from http://sat.belastro.net/satelliteorbitdetermination.com/RV2EL.txt, the state vector differences between `poliastro` and `spg4` are down to centimetre-level, which is much more in line with expectations.

See result of [run.py](https://github.com/jtegedor/rv2tle/blob/master/run.py) here:

```
$ ./run.py 
WARNING: AstropyDeprecationWarning: The private astropy._erfa module has been made into its own package, pyerfa, which is a dependency of astropy and can be imported directly using "import erfa" [astropy._erfa]
 Orbit: 6772 x 6790 km x 51.6 deg (GCRS) orbit around Earth (♁) at epoch 2013-03-18 12:00:00.000 (UTC)
 State vector [poliastro]
     r = [  859.07256 -4137.20368  5295.56871] km
     v = [7.37289205 2.08223573 0.43999979] km / s

                Poliastro(osc)       rv2tle.rv2el(mean)
Ecc            :       0.00131                  0.00124
Incl  [deg]    :      51.60121                 51.64622
n [deg/min]    :       3.88701                  3.88235
RAAN  [deg]    :     198.37950                198.60099
Argp + M [deg] :      85.75009                 85.65659

State vector [rv2el/spg4]
     r = [  859.07254846 -4137.20360516  5295.56864002] km
     v = [7.37289209 2.08223579 0.43999983] km / s

State vector differences [poliastro - rv2el/spg4]
    dr = [ 1.15402148e-05 -7.48448565e-05  6.99806860e-05] km
    dv = [-4.10360785e-08 -6.04953607e-08 -3.29464049e-08] km / s
```

@astrojuanlu, the question is whether the transformation from state vector to mean orbital elements should be done inside `poliastro`, in order to offer a working interface to `spg4`.

**Comment by astrojuanlu** [comment] 2021-05-05 19:11
Happy you got this almost working @jtegedor ! There might be a reason for the centimeter differences, although I assume these are good enough to get started.

> @astrojuanlu, the question is whether the transformation from state vector to mean orbital elements should be done inside poliastro, in order to offer a working interface to spg4.

Exactly, and I think this would be a great addition.

**Comment by astrojuanlu** [comment] 2021-05-08 11:15
By the way @jtegedor I just realized that https://github.com/jtegedor/rv2tle/blob/master/rv2tle.py is yours. Would you like to contribute it to poliastro under the MIT license? (Notice that, for this,  Please have a look at https://github.com/poliastro/poliastro/tree/main/contrib Later on we can work on adding it to our API.

**Comment by jtegedor** [comment] 2021-05-09 06:57
@astrojuanlu, PR has been created. This is the first one for me, so please have a look and check that it is within expectations.

**Comment by astrojuanlu** [comment] 2021-05-09 22:41
Merged! 🚀 I'm closing this support issue in favor of https://github.com/poliastro/poliastro/issues/1215, which I think it's the first step towards providing a proper API.

**Closed by astrojuanlu** 2021-05-09 22:41 UTC
Labels: support
