### ISSUE TITLE
Documentation build error

### ISSUE THREAD

**Issue by Yash-10** [poliastro/poliastro#1303] opened 2021-08-11 18:32 UTC
Running `make html` for building docs, I got an error:

```bash
Notebook error:
CellExecutionError in examples/Analyzing NEOs.mystnb:
------------------
eros = Orbit.from_sbdb("Eros")
eros.plot(label="Eros");
------------------

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/poliastro/poli/lib/python3.8/site-packages/poliastro/frames/util.py in get_frame(attractor, plane, obstime)
     77     try:
---> 78         frames = _FRAME_MAPPING[attractor]
     79     except KeyError:

KeyError: Sun (☉)

During handling of the above exception, another exception occurred:

NotImplementedError                       Traceback (most recent call last)
/tmp/ipykernel_41780/3598702949.py in <module>
      1 eros = Orbit.from_sbdb("Eros")
----> 2 eros.plot(label="Eros");

~/poliastro/poli/lib/python3.8/site-packages/poliastro/twobody/orbit.py in plot(self, label, use_3d, interactive)
   1456             from poliastro.plotting.static import StaticOrbitPlotter
   1457 
-> 1458             return StaticOrbitPlotter().plot(self, label=label)
   1459         elif use_3d:
   1460             from poliastro.plotting.core import OrbitPlotter3D

~/poliastro/poli/lib/python3.8/site-packages/poliastro/plotting/static.py in plot(self, orbit, label, color, trail)
    213             self.set_orbit_frame(orbit)
    214 
--> 215         lines = self._plot(orbit, label=label, color=color, trail=trail)
    216         lines = lines[0] + [lines[1]]
    217 

~/poliastro/poli/lib/python3.8/site-packages/poliastro/plotting/_base.py in _plot(self, orbit, label, color, trail)
    151         self.set_attractor(orbit.attractor)
    152 
--> 153         orbit = orbit.change_plane(self.plane)
    154 
    155         label = generate_label(orbit.epoch, label)

~/poliastro/poli/lib/python3.8/site-packages/poliastro/twobody/orbit.py in change_plane(self, plane)
    573             return self
    574 
--> 575         coords_orig = self.get_frame().realize_frame(
    576             self.represent_as(CartesianRepresentation, CartesianDifferential)
    577         )

~/poliastro/poli/lib/python3.8/site-packages/poliastro/twobody/orbit.py in get_frame(self)
    501             return self._frame
    502 
--> 503         return get_frame(self.attractor, self.plane, self.epoch)
    504 
    505     def change_attractor(self, new_attractor, force=False):

~/poliastro/poli/lib/python3.8/site-packages/poliastro/frames/util.py in get_frame(attractor, plane, obstime)
     78         frames = _FRAME_MAPPING[attractor]
     79     except KeyError:
---> 80         raise NotImplementedError(
     81             "Frames for orbits around custom bodies are not yet supported"
     82         )

NotImplementedError: Frames for orbits around custom bodies are not yet supported
NotImplementedError: Frames for orbits around custom bodies are not yet supported

You can ignore this error by setting the following in conf.py:

    nbsphinx_allow_errors = True

make: *** [Makefile:61: html] Error 2
```

I initially thought a possible reason for this error might be: Some days ago, the `Sun` was made a `Body` instance instead of a `SolarSystemPlanet` instance. However, this seems to be related to documentation somehow.

Would love to know opinions on this and if this error is reproducible.

`pip freeze` output:

<details>

```
alabaster==0.7.12
appdirs==1.4.4
argon2-cffi==20.1.0
astroid==2.6.6
astropy==4.3.post1
astroquery==0.4.3
async-generator==1.10
attrs==21.2.0
Babel==2.9.1
backcall==0.2.0
beautifulsoup4==4.9.3
black==21.5b0
bleach==4.0.0
certifi==2021.5.30
cffi==1.14.6
charset-normalizer==2.0.4
click==8.0.1
coverage==5.5
cryptography==3.4.7
cycler==0.10.0
czml3==0.5.4
debugpy==1.4.1
decorator==5.0.9
defusedxml==0.7.1
docutils==0.17.1
entrypoints==0.3
filelock==3.0.12
flit==3.3.0
flit-core==3.3.0
html5lib==1.1
hypothesis==6.14.6
idna==3.2
imagesize==1.2.0
importlib-metadata==4.6.3
iniconfig==1.1.1
ipykernel==6.0.3
ipython==7.26.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
isort==5.9.3
jedi==0.18.0
jeepney==0.7.1
Jinja2==3.0.1
jplephem==2.16
jsonschema==3.2.0
jupyter-client==6.1.12
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0
jupytext==1.11.4
keyring==23.0.1
kiwisolver==1.3.1
lazy-object-proxy==1.6.0
llvmlite==0.36.0
markdown-it-py==1.1.0
MarkupSafe==2.0.1
matplotlib==3.4.2
matplotlib-inline==0.1.2
mdit-py-plugins==0.2.8
mimeparse==0.1.3
mistune==0.8.4
mypy==0.910
mypy-extensions==0.4.3
myst-parser==0.15.1
nbclient==0.5.3
nbconvert==6.1.0
nbformat==5.1.3
nbsphinx==0.8.7
nest-asyncio==1.5.1
notebook==6.4.3
numba==0.53.1
numpy==1.21.1
packaging==21.0
pandas==1.3.1
pandocfilters==1.4.3
parso==0.8.2
pathspec==0.9.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.3.1
plotly==5.1.0
pluggy==0.13.1
poliastro==0.16.dev0
prometheus-client==0.11.0
prompt-toolkit==3.0.19
ptyprocess==0.7.0
py==1.10.0
pycodestyle==2.7.0
pycparser==2.20
pyerfa==2.0.0
Pygments==2.9.0
pyparsing==2.4.7
pyrsistent==0.18.0
pytest==6.2.4
pytest-cov==2.5.1
pytest-doctestplus==0.10.1
pytest-mpl==0.13
pytest-mypy==0.8.1
pytest-remotedata==0.3.2
python-dateutil==2.8.2
pytz==2021.1
pyvo==1.1
PyYAML==5.4.1
pyzmq==22.2.1
regex==2021.8.3
requests==2.26.0
scipy==1.7.1
SecretStorage==3.3.1
Send2Trash==1.8.0
six==1.16.0
snowballstemmer==2.1.0
sortedcontainers==2.4.0
soupsieve==2.2.1
Sphinx==4.1.2
sphinx-autoapi==1.8.3
sphinx-gallery==0.9.0
sphinx-hoverxref==0.7b1
sphinx-notfound-page==0.7.1
sphinx-rtd-theme==0.5.2
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
tenacity==8.0.1
terminado==0.10.1
testpath==0.5.0
toml==0.10.2
tornado==6.1
traitlets==5.0.5
typing-extensions==3.10.0.0
Unidecode==1.2.0
urllib3==1.26.6
w3lib==1.22.0
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
wrapt==1.12.1
zipp==3.5.0
```

</details>

Thanks!

**Comment by jorgepiloto** [comment] 2021-08-13 09:29
I was facing the same problem but after a clean poliastro installation in a fresh-new virtual environment this was solved 🤔

**Comment by Yash-10** [comment] 2021-08-13 09:37
debug output:

<details>

```
ipdb> p Sun
Sun (☉)
ipdb> p attractor is Sun
True
ipdb> p Sun in _FRAME_MAPPING
False
ipdb> p attractor in _FRAME_MAPPING
False
ipdb> p Sun is list(_FRAME_MAPPING.keys())
False
ipdb> p Sun in list(_FRAME_MAPPING.keys())
True
ipdb> p Sun is list(_FRAME_MAPPING.keys()[0])
*** TypeError: 'dict_keys' object is not subscriptable
ipdb> p Sun is list(_FRAME_MAPPING.keys())[0]
True
ipdb> _FRAME_MAPPING
{Sun (☉): {<Planes.EARTH_EQUATOR: 'Earth mean Equator and Equinox of epoch (J2000.0)'>: <class 'astropy.coordinates.builtin_frames.hcrs.HCRS'>, <Planes.EARTH_ECLIPTIC: 'Earth mean Ecliptic and Equinox of epoch (J2000.0)'>: <class 'astropy.coordinates.builtin_frames.ecliptic.HeliocentricEclipticIAU76'>}, Mercury (☿): {<Planes.EARTH_EQUATOR: 'Earth mean Equator and Equinox of epoch (J2000.0)'>: <class 'poliastro.frames.equatorial.MercuryICRS'>, <Planes.BODY_FIXED: 'Rotating body mean Equator and node of date'>: <class 'poliastro.frames.fixed.MercuryFixed'>}, Venus (♀): {<Planes.EARTH_EQUATOR: 'Earth mean Equator and Equinox of epoch (J2000.0)'>: <class 'poliastro.frames.equatorial.VenusICRS'>, <Planes.BODY_FIXED: 'Rotating body mean Equator and node of date'>: <class 'poliastro.frames.fixed.VenusFixed'>}, Earth (♁): {<Planes.EARTH_EQUATOR: 'Earth mean Equator and Equinox of epoch (J2000.0)'>: <class 'astropy.coordinates.builtin_frames.gcrs.GCRS'>, <Planes.EARTH_ECLIPTIC: 'Earth mean Ecliptic and Equinox of epoch (J2000.0)'>: <class 'astropy.coordinates.builtin_frames.ecliptic.GeocentricMeanEcliptic'>, <Planes.BODY_FIXED: 'Rotating body mean Equator and node of date'>: <class 'astropy.coordinates.builtin_frames.itrs.ITRS'>}, Mars (♂): {<Planes.EARTH_EQUATOR: 'Earth mean Equator and Equinox of epoch (J2000.0)'>: <class 'poliastro.frames.equatorial.MarsICRS'>, <Planes.BODY_FIXED: 'Rotating body mean Equator and node of date'>: <class 'poliastro.frames.fixed.MarsFixed'>}, Jupiter (♃): {<Planes.EARTH_EQUATOR: 'Earth mean Equator and Equinox of epoch (J2000.0)'>: <class 'poliastro.frames.equatorial.JupiterICRS'>, <Planes.BODY_FIXED: 'Rotating body mean Equator and node of date'>: <class 'poliastro.frames.fixed.JupiterFixed'>}, Saturn (♄): {<Planes.EARTH_EQUATOR: 'Earth mean Equator and Equinox of epoch (J2000.0)'>: <class 'poliastro.frames.equatorial.SaturnICRS'>, <Planes.BODY_FIXED: 'Rotating body mean Equator and node of date'>: <class 'poliastro.frames.fixed.SaturnFixed'>}, Uranus (⛢): {<Planes.EARTH_EQUATOR: 'Earth mean Equator and Equinox of epoch (J2000.0)'>: <class 'poliastro.frames.equatorial.UranusICRS'>, <Planes.BODY_FIXED: 'Rotating body mean Equator and node of date'>: <class 'poliastro.frames.fixed.UranusFixed'>}, Neptune (♆): {<Planes.EARTH_EQUATOR: 'Earth mean Equator and Equinox of epoch (J2000.0)'>: <class 'poliastro.frames.equatorial.NeptuneICRS'>, <Planes.BODY_FIXED: 'Rotating body mean Equator and node of date'>: <class 'poliastro.frames.fixed.NeptuneFixed'>}}
ipdb> _FRAME_MAPPING.keys()
dict_keys([Sun (☉), Mercury (☿), Venus (♀), Earth (♁), Mars (♂), Jupiter (♃), Saturn (♄), Uranus (⛢), Neptune (♆)])
ipdb> list(_FRAME_MAPPING.keys())
*** Error in argument: '(_FRAME_MAPPING.keys())'
ipdb> p list(_FRAME_MAPPING.keys())
[Sun (☉), Mercury (☿), Venus (♀), Earth (♁), Mars (♂), Jupiter (♃), Saturn (♄), Uranus (⛢), Neptune (♆)]
ipdb> p list(_FRAME_MAPPING.keys())[0]
Sun (☉)
ipdb> p type(list(_FRAME_MAPPING.keys())[0])
<class 'poliastro.bodies.Body'>
```
</details>

**Comment by astrojuanlu** [comment] 2021-08-13 10:36
I installed these dependencies on Python 3.8.10 and I still can't reproduce the issue using poliastro 6b9e5a2e. The problem here is that at the moment it isn't possible to know what development version is installed, so probably we will have to work on improving that.

I asked @Yash-10 to send us his zipped environment, in case there is something else that is broken.

In any case, I find this particularly astonishing:

```
ipdb> p Sun in _FRAME_MAPPING
False
ipdb> p Sun in list(_FRAME_MAPPING.keys())
True
```

**Comment by Yash-10** [comment] 2021-08-13 12:54
Yeah! Here is the zipped environment: https://drive.google.com/file/d/1fsSdA09riXs1S4zxOCHggaqwCtah-Ayy/view?usp=sharing. Hope we resolve this soon :)

**Comment by astrojuanlu** [comment] 2021-08-15 08:33
Well, I can't reproduce the issue even after replacing my `site-packages` with yours. At the moment, the only thing I can say is: `rm -rf` your environment and create a new one :/

**Comment by Yash-10** [comment] 2021-08-15 10:22
I didn't change anything in my environment but the error doesn't appear now! Documentation build seems to be fine too...

**Comment by astrojuanlu** [comment] 2021-08-15 11:28
Unfortunately, it will remain a mistery. Let's close this!

**Closed by astrojuanlu** 2021-08-15 11:28 UTC
Labels: needs more info
