### ISSUE TITLE
matching to STK J2 propagator

### ISSUE THREAD

**Issue by astrostates** [poliastro/poliastro#1220] opened 2021-05-13 02:34 UTC
I am trying to setup a J2 propagator using the following modules:

```
from poliastro.twobody import orbit
from poliastro import constants
from poliastro.bodies import Earth
from poliastro.core.perturbations import J2_perturbation
from poliastro.twobody.propagation import propagate, cowell
```

Following the users guide,  I generate an Orbit object and then propagate it with the two commands below.

```
sim_object_propagator = orbit.Orbit.from_classical(Earth, sim_object.sma, sim_object.ecc, sim_object.inc, sim_object.raan,
                                                           sim_object.arg_of_per, sim_object.true_anom,  epoch=epoch_time)

 sim_object_prop_data = propagate(sim_object_propagator, prop_times, method=cowell, ad=J2_perturbation, J2=Earth.J2.value, R=Earth.R.to(u.km).value)
```

I have tried to match the output with the STK J2 propagator and tried several different coordinate systems.   The two algorithms always drift away from each other.   Does anybody know any settings (in STK or poliasto) that exist so they match up.

**Comment by jorgepiloto** [comment] 2021-05-13 08:23
Hi @astrostates ,

let me ask you a question first, ¿are you using poliastro==0.14 or poliastro==0.15b1?

If you are using 0.14 version, results are expected to match using the logic you applied before. If not, this deserves more investigation.

On the other hand, if using 0.15, the way to define custom perturbation function has changed. Some months ago, the API for Cowell's propagator was refactored and now a single function `f` is needed, see the [an example](https://docs.poliastro.space/en/latest/quickstart.html#studying-non-keplerian-orbits-perturbations) from latest documentation.

Let us know once you have tested previous tips!

**Comment by astrostates** [comment] 2021-05-13 13:20
Hi Jorge,

Thank you for the quick response.    I am using 0.14.   It does not match for the way I am setting it up.   I feel there is something I am not setting up correctly, but I cannot figure out what.    Later tonight,  I will send you a .py script and an excel output of the results I get compared to STK.

Thanks again,

Bob

**Comment by sammmlow** [comment] 2021-05-13 13:43
Hi @astrostates, I'm a frequent STK user so maybe I can help. Could you paste an image of your STK propagator settings? Are both STK and your code in poliastro starting the propagation with true anomaly? Do they both start at the same exact position in the same coordinate frame?

Maybe as a sanity check, you might want to compare just the two-body propagator between poliastro and STK as a start and see if there is a position drift over time.

Another possibility: Sometimes there are floating point decimals in the STK input text entries (i.e. semi-major axis) for the orbit elements that are not captured by the UI (for example the UI shows 6678.14km but the report graph is actually 6678.1365 as shown in the images below) so that could explain the drift between the STK and poliastro values.

![image](https://user-images.githubusercontent.com/17903127/118134103-219a6e00-b434-11eb-9d83-fe1c26a40097.png)

![image](https://user-images.githubusercontent.com/17903127/118134165-31b24d80-b434-11eb-82b5-7dbd4d195540.png)

Just throwing out ideas.

**Comment by jorgepiloto** [comment] 2021-05-13 13:45
So cool @sammmlow! I was going to suggest for someone familiar with STK to replicate this but you were faster 🚀

**Comment by sammmlow** [comment] 2021-05-13 13:49
I just happened to see this at the right time, I hope I can be of help 😄

**Comment by astrostates** [comment] 2021-05-13 13:56
hi @sammmlow,

Thanks for your response.   To answer your questions,   Poliastro reports the exact same starting position as STK.   If I run both just as twobody,  They do not drift and match very well over time.   The J2 drift I think is much higher than what would be caused by a few meter difference in the settings, but I am not sure.  I will confirm.  Later today, I will package up and post all that I am seeing.   Thanks for your help....

**Comment by astrostates** [comment] 2021-05-13 18:34
Hi @sammmlow @jorgepiloto 

[Poliastro_Test_Results.xlsx](https://github.com/poliastro/poliastro/files/6474377/Poliastro_Test_Results.xlsx)
  attached are the comparison between poliastro and STK (in spreadsheet).  I also attached the code I used to generate the poliastro data and a screenshot of the STK satellite initialization.   I only changed the propagatgor tab from twobody to J2 to generate the STK data.    Notice the J2 results diverging quickly.    Any suggestions as to the cause would be greatly appreciated.

[Poliastro_Test_Results.xlsx](https://github.com/poliastro/poliastro/files/6474384/Poliastro_Test_Results.xlsx)
![Capture](https://user-images.githubusercontent.com/84112658/118170153-c5b1f400-b3f7-11eb-9f05-d90c540eed4c.PNG)



from poliastro.twobody import orbit
from poliastro import constants
from poliastro.bodies import Earth
from poliastro.core.perturbations import J2_perturbation
from poliastro.twobody.propagation import propagate, cowell
from poliastro import constants
from astropy import units as u
from astropy.time import Time, TimeDelta
import numpy as np
import pandas as pd

Satellite_apogee = 500 * u.km
Satellite_perigee = 500 * u.km
Satellite_inc = 45 * u.deg
Satellite_raan = 0 * u.deg
Satellite_arg_of_per = 0 * u.deg
Satellite_true_anom = 0 * u.deg
Satellite_epoch = '2021-05-12 16:00:00.0'

epoch_time = Time(Satellite_epoch, format='iso', scale='utc')
sim_length = 1*u.day
sim_resolution = 1*u.min
num_times = (sim_length / sim_resolution).decompose().value
prop_times = TimeDelta(np.linspace(0, sim_length, num=(int(num_times) + 1)))

rad_earth = constants.R_earth
Satellite_sma = (Satellite_apogee + Satellite_perigee + rad_earth*2)/2
Satellite_ecc = (Satellite_apogee + rad_earth)/Satellite_sma - 1

sim_object_propagator = orbit.Orbit.from_classical(Earth, Satellite_sma, Satellite_ecc, Satellite_inc, Satellite_raan,
                                                   Satellite_arg_of_per, Satellite_true_anom,  epoch=epoch_time)
sim_object_prop_data_J2 = propagate(sim_object_propagator, prop_times, method=cowell, ad=J2_perturbation, J2=Earth.J2.value, R=Earth.R.to(u.km).value)
sim_object_prop_data_twobody = propagate(sim_object_propagator, prop_times)

xx = pd.DataFrame(sim_object_prop_data_J2)

with pd.ExcelWriter('Poliastro_Test_Results.xlsx') as writer:
    J2_Data_df = pd.DataFrame(sim_object_prop_data_J2.xyz.T, columns=['ECI_x_km', 'ECI_Y_km', 'ECI_Z_km'])
    Twobody_Data_df = pd.DataFrame(sim_object_prop_data_twobody.xyz.T, columns=['ECI_x_km', 'ECI_Y_km', 'ECI_Z_km'])
    J2_Data_df.to_excel(writer, sheet_name='J2_Data', index=False, header=True)
    Twobody_Data_df.to_excel(writer, sheet_name='TwoBody_Data', index=False, header=True)

**Comment by sammmlow** [comment] 2021-05-14 05:10
OK I replicated your problem by comparing my PoliAstro and STK results too. The oscillations in those ephemeris differences have a period of about 95 minutes which is the same as the Keplerian period. I don't have a good answer to why this happened at the moment, as I'm not familiar with how the J2 propagation was implemented in PoliAstro...

Can you try to propagate it for a longer duration, maybe a week or so, and see if the ephemeris differences diverge (it looks like it is an oscillating divergence in your plot but that's only for 1 day of propagation). Or, do they just kind of oscillate back about zero? If there is secular divergence then might be an accumulating numerical error somewhere in the J2 propagation.

**Comment by astrostates** [comment] 2021-05-14 15:46
I ran a 10 day run and 90 day run.   Data attached.   I think the error is secular.   The oscillation is just the orbit eventually coming back to itself..
[Poliastro_Test_Results_10days.xlsx](https://github.com/poliastro/poliastro/files/6479813/Poliastro_Test_Results_10days.xlsx)
[Poliastro_Test_Results_90 days.xlsx](https://github.com/poliastro/poliastro/files/6479814/Poliastro_Test_Results_90.days.xlsx)

**Comment by sammmlow** [comment] 2021-05-15 01:16
Hmm yes, I ran some experiments between the two softwares and checked that it's not an issue between differences in the J2 constant or differences in Earth radii used in computation between PoliAstro and STK. After correcting for these (minor decimal places), I am still getting 600km RMS error after 1440 min of orbit.

![image](https://user-images.githubusercontent.com/17903127/118343880-062b8200-b55e-11eb-8057-7ac328bd5738.png)

I can't add value to this issue at the moment, as I'm not familiar with the implementation of Cowell's propagator using the J2 perturbation, in PoliAstro. Anyone with a better idea?

**Comment by astrojuanlu** [comment] 2021-05-16 18:56
Thanks a lot @astrostates and @sammmlow for this investigation! I wonder if looking at the data in terms of Keplerian elements adds a bit more information? Our `cowell` propagator is validated against lots of test cases from the literature as well as the rest of the analytical propagators, so I find it weird that there's such a large error after only 24 hours. However, I agree it's important to find out what's wrong here. I wonder what's the output of GMAT and Orekit? Something to add to our validation framework @jorgepiloto ?

**Comment by jorgepiloto** [comment] 2021-05-16 20:17
I saw the position after 1 day of propagation within @astrostates shared files do not match, which is weird because initial conditions are the same. In addition, a quick test with GMAT (via GUI) raised different results from poliastro's ones... However, I checked more literature examples and the results from our current implementation agree with those. 

Therefore, as suggested by @astrojuanlu, I will validate this against Orekit and GMAT (this time using script) to guess what is going on here 🤔

**Comment by astrojuanlu** [comment] 2021-10-04 07:00
Reopening, since we still might have a problem here.

**Comment by manweichan** [comment] 2022-01-11 22:46
Trying to pick up where this thread left off last time! I changed the workflow a bit where I generated the orbit in STK, and then imported the initial conditions to instantiate the orbit with Poliastro, hoping to avoid any lost digits if instantiating both STK and Poliastro orbits separately. I was able to recreate the position errors for the STK example above. Following @astrojuanlu's suggestion, I plotted the orbit in terms of the orbital elements. Overall it looks like STK tries to only vary RAAN with it's J2 propagator, but keeps the other elements constant. The argument of perigee is funky, but I'm guessing that's numerical error for the circular orbit. Something somewhat funky is also happening with the true anomaly and the way angles are handled (could that also be a numerical artifact)? I'm still not sure why the overall position error rises to 700 km over a day.
![semimajor](https://user-images.githubusercontent.com/17070627/149031594-a73b0e5d-1d38-4c96-8a2e-bca11c435b95.png)
![ecc](https://user-images.githubusercontent.com/17070627/149031602-810e42d4-5446-4ac3-abe6-101981bf447b.png)
![inc](https://user-images.githubusercontent.com/17070627/149031613-7fa363f0-22d1-497d-b3fc-02fd37f8633c.png)
![raan](https://user-images.githubusercontent.com/17070627/149031622-a9374fed-0c77-4668-a54e-784afb240d1f.png)
![argp](https://user-images.githubusercontent.com/17070627/149031634-cd5a10ff-bc87-4657-b54d-0a722f0b607c.png)
![nu](https://user-images.githubusercontent.com/17070627/149031647-7559785d-fdfe-4521-9f96-22b9f54ebdc8.png)

Here's a quick snippet of the code I used to get the orbital elements (it probably wasn't the most efficient way to extract the elements). f is defined as the J2 example in the docs. rv2coe was taken from poliastro.core.elements

    # Propagate
    poliCoords = propagate(
        poliOrb,
        tofs,
        method=cowell,
        f=f,
    )

    coe_a = np.empty(len(poliCoords))
    coe_ecc = np.empty(len(poliCoords))
    coe_inc = np.empty(len(poliCoords))
    coe_raan = np.empty(len(poliCoords))
    coe_argp = np.empty(len(poliCoords))
    coe_nu = np.empty(len(poliCoords))

    #Extract to COE
    k = Earth.k.to_value(u.km**3/u.s**2)
    for idx in range(0, len(poliCoords)):
        r_x = poliCoords[idx].x.to(u.km).value
        r_y = poliCoords[idx].y.to(u.km).value
        r_z = poliCoords[idx].z.to(u.km).value
        rr=np.squeeze(np.array([r_x, r_y, r_z]))
        
        v_x = poliCoords.differentials['s'][idx].d_x.to(u.km/u.s).value
        v_y = poliCoords.differentials['s'][idx].d_y.to(u.km/u.s).value
        v_z = poliCoords.differentials['s'][idx].d_z.to(u.km/u.s).value
        vv = np.squeeze(np.array([v_x, v_y, v_z]))
        
        p, ecc, inc, raan, argp, nu = rv2coe(k, rr, vv)
        a = p / (1-ecc**2)
        
        coe_a[idx] = a
        coe_ecc[idx] = ecc
        coe_inc[idx] = np.rad2deg(inc)
        coe_raan[idx] = np.rad2deg(raan)
        coe_argp[idx] = np.rad2deg(argp)
        coe_nu[idx] = np.rad2deg(nu)

**Comment by astrojuanlu** [comment] 2022-01-11 22:56
This is very useful @manweichan , thanks a lot! Can you share the initial conditions as well so I can try to reproduce it?

I'm wondering if this could be caused by numerical error, but that oscillations look suspicious. Notice that we don't have an analytical J2 propagator (#285).

**Comment by astrojuanlu** [comment] 2022-01-11 22:56
Regarding the angles, I think for circular orbits it only makes sense to plot argp + nu, and raan + argp + nu in case they're also equatorial.

**Comment by sammmlow** [comment] 2022-01-11 23:10
I can add comment here that STK performs J2 propagation by applying the variational equations (up to J2 only) directly to the osculating elements. This means actually applying the derivative of the RAAN, ARGP, etc. Whereas Cowell's method in Poliastro (if I'm not mistake) performs numerical integration of the Cartesian states using the acceleration vector inclusive of J2. This should explain differences in why they differ, they are both correct, just using different models is my guess 😄

**Comment by astrojuanlu** [comment] 2022-01-11 23:22
> I verified that this gives same order of magnitude of errors too within STK, by performing J2 propagation using STK's numerical integrator with geopotential degree and order [2,0], and using STK's J2 propagator (which directly applies changes to osculating elements).

Interesting! So the Cowell propagator of poliastro with J2 is more or less = the numerical propagator of STK with J2 then?

**Comment by manweichan** [comment] 2022-01-11 23:27
Very interesting! I'll see if I can compare the numerical STK propagator to the poliastro Cowell's method to see if they agree!

In the meantime, here are the initial conditions, if you still want them

```
x (km): 6878.137000
y (km): -0.000000
z (km): -0.000000
dx (km/s): 0.000000
dy (km/s): 5.382927
dz (km/s): 5.382927
```

**Comment by sammmlow** [comment] 2022-01-11 23:34
This was OP's original plot using STK J2 (standard) versus PoliAstro J2 on Cowell:
![image](https://user-images.githubusercontent.com/17903127/149037750-ba254add-a300-4462-b21b-862ccef016b2.png)

This is using STK J2 but on numerical propagation RKF78, versus PoliAstro J2 on Cowell:
![image](https://user-images.githubusercontent.com/17903127/149037785-fdee7669-1f7e-4488-80e4-bef8832dd80a.png)

Errors have dramatically reduced 3 orders of magnitude just from switching the perturbation model. Time lapse was 1 day, time step 60 seconds :)

So yes, it is because of the difference in applying the perturbation models it seems. The residual errors could be other things like different numerical integrators.

**Comment by manweichan** [comment] 2022-01-12 00:22
Thanks @sammmlow! I agree, the errors are probably artifacts from the integrator and other underlying features. I ran it as well and got similar results. Attached the position errors ~1km after a day and also the STK settings I used (turned off all other external forces) for reference.
![posErrnumerical](https://user-images.githubusercontent.com/17070627/149040702-fe4c479c-4302-416c-bc36-8e0001f53f06.png)
![Screenshot_force_model](https://user-images.githubusercontent.com/17070627/149040847-f94d1787-4dc8-4401-a030-6d9179027320.png)

**Comment by astrojuanlu** [comment] 2022-01-12 12:26
Mistery solved! Thanks all for your help!

There are two things here:

- Mathematical differences between a numerical J2 propagation and an analytical J2 propagation that only affects the precession of the node, regardless of implementation. Would be cool to investigate more.
- Small numerical differences between STK RKF78 + J2 and poliastro DOP853 + J2. In principle, we will assume that they can be attributed to small differences in the constants or the numerical integration methods. And in any case, ~1 km in ~1 day is much less than any other propagation error (usual TLE errors are in this order if I recall correctly for example).

I am closing this issue, feel free to continue the discussion!

**Closed by astrojuanlu** 2022-01-12 12:26 UTC
Labels: bug

**Comment by atergt** [comment] 2022-05-25 09:57
> This is very useful @manweichan , thanks a lot! Can you share the initial conditions as well so I can try to reproduce it?
> 
> I'm wondering if this could be caused by numerical error, but that oscillations look suspicious. Notice that we don't have an analytical J2 propagator (#285).

Hi, I am reopening this since I am getting weird results when using the J2 propagator for orbits with eccentricity less than 0.01 (which is most of them).  I have problems with the argument of perigee and true anomaly, they vary weirdly wrt what I would expect.

![image](https://user-images.githubusercontent.com/102949019/170235628-d95b2ff4-a7c2-4236-9c39-0a08c7eca99a.png)
![image](https://user-images.githubusercontent.com/102949019/170235709-7c326303-8cd0-4d96-8e76-9800d5683111.png)

These are my initial conditions and I propagated for 2 days

a_c0 = 6878.14 * u.km  # initial semi-major axis [km]
e_c0 = 5.46337e-16 * u.one  # initial eccentricity [/]
i_c0 = 97.5435 * u.deg  # initial inclination [deg]
RA_c0 = 101.075 * u.deg  # initial RAAN [deg]
w_c0 = 0 * u.deg  # initial argument of perigee [deg]
TA_c0 = 0.0250131 * u.deg  # initial true anomaly [deg].

Can you help me understand what's happening?

**Comment by astrojuanlu** [comment] 2022-05-25 11:17
Hi @atergt, could you open a new issue, including the code you're using, so we can try to reproduce?
