### ISSUE TITLE
`build_ephem_interpolant` throws an unhelpful `TypeError` if the `period` is too large

### ISSUE THREAD

**Issue by Nosudrum** [poliastro/poliastro#1506] opened 2022-05-20 08:17 UTC
🐞 **Problem**

Opening this issue following the discussion in https://github.com/poliastro/poliastro/issues/1504.
The `poliastro` version used here is directly installed from the `main` branch.

When trying to build an ephem interpolant for the `Sun` using `build_ephem_interpolant`, a `TypeError` is thrown by `astropy\coordinates\baseframe.py`.

Here is a concise code to reproduce the issue :
```python
from datetime import datetime
from astropy import units as u
from astropy.time import Time
from poliastro.bodies import Sun
from poliastro.ephem import build_ephem_interpolant

# Setup start/end epochs
start_epoch = datetime(2020, 1, 1, 0, 0, 0)
end_epoch = datetime(2020, 1, 2, 0, 0, 0)

# Create Time objects
start_epoch_Time_obj = Time(start_epoch, scale='utc')
end_epoch_Time_obj = Time(end_epoch, scale='utc')

# Build the Sun ephemeris interpolant
Sun_r = build_ephem_interpolant(Sun, 1 * u.year,
                                (start_epoch_Time_obj.to_value("jd") << u.d, end_epoch_Time_obj.to_value("jd") << u.d),
                                rtol=1e-2)
```
Running it results in the following error :
```python
Traceback (most recent call last):
  File "C:\Users\a.muller\Anaconda3\envs\poliastro-main\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\a.muller\AppData\Local\JetBrains\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Users\a.muller\AppData\Local\JetBrains\PyCharm 2022.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/a.muller/Documents/GitHub/2022_muller_arnaud/poliastro-main/issues_reproducers/Sun_ephem.py", line 21, in <module>
    Sun_r = build_ephem_interpolant(Sun, 1 * u.year,
  File "C:\Users\a.muller\Anaconda3\envs\poliastro-main\lib\site-packages\poliastro\ephem.py", line 56, in build_ephem_interpolant
    ephem = Ephem.from_body(body, epochs, attractor=attractor)
  File "C:\Users\a.muller\Anaconda3\envs\poliastro-main\lib\site-packages\poliastro\ephem.py", line 228, in from_body
    ICRS(coordinates)
  File "C:\Users\a.muller\Anaconda3\envs\poliastro-main\lib\site-packages\astropy\coordinates\baseframe.py", line 1045, in represent_as
    raise TypeError('Frame data has no associated differentials '
TypeError: Frame data has no associated differentials (i.e. the frame has no velocity data) - represent_as() only accepts a new representation.
```

🖥 **Please paste the output of following commands**

<details>

<summary> conda info -a </summary>

```bash
(poliastro-main) PS C:\> conda info -a

     active environment : poliastro-main
    active env location : C:\Users\a.muller\Anaconda3\envs\poliastro-main
            shell level : 2
       user config file : C:\Users\a.muller\.condarc
 populated config files : C:\Users\a.muller\.condarc
          conda version : 4.12.0
    conda-build version : 3.21.6
         python version : 3.9.7.final.0
       virtual packages : __cuda=11.3=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\a.muller\Anaconda3  (writable)
      conda av data dir : C:\Users\a.muller\Anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/tudat-team/win-64
                          https://conda.anaconda.org/tudat-team/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\a.muller\Anaconda3\pkgs
                          C:\Users\a.muller\.conda\pkgs
                          C:\Users\a.muller\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\a.muller\Anaconda3\envs
                          C:\Users\a.muller\.conda\envs
                          C:\Users\a.muller\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.12.0 requests/2.26.0 CPython/3.9.7 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False

# conda environments:
#
base                     C:\Users\a.muller\Anaconda3
orekit-python            C:\Users\a.muller\Anaconda3\envs\orekit-python
poliastro                C:\Users\a.muller\Anaconda3\envs\poliastro
poliastro-main        *  C:\Users\a.muller\Anaconda3\envs\poliastro-main
tudat-space              C:\Users\a.muller\Anaconda3\envs\tudat-space

sys.version: 3.9.7 (default, Sep 16 2021, 16:59:28) [...
sys.prefix: C:\Users\a.muller\Anaconda3
sys.executable: C:\Users\a.muller\Anaconda3\python.exe
conda location: C:\Users\a.muller\Anaconda3\lib\site-packages\conda
conda-build: C:\Users\a.muller\Anaconda3\Scripts\conda-build.exe
conda-content-trust: C:\Users\a.muller\Anaconda3\Scripts\conda-content-trust.exe
conda-convert: C:\Users\a.muller\Anaconda3\Scripts\conda-convert.exe
conda-debug: C:\Users\a.muller\Anaconda3\Scripts\conda-debug.exe
conda-develop: C:\Users\a.muller\Anaconda3\Scripts\conda-develop.exe
conda-env: C:\Users\a.muller\Anaconda3\Scripts\conda-env.exe
conda-index: C:\Users\a.muller\Anaconda3\Scripts\conda-index.exe
conda-inspect: C:\Users\a.muller\Anaconda3\Scripts\conda-inspect.exe
conda-metapackage: C:\Users\a.muller\Anaconda3\Scripts\conda-metapackage.exe
conda-pack: C:\Users\a.muller\Anaconda3\Scripts\conda-pack.exe
conda-render: C:\Users\a.muller\Anaconda3\Scripts\conda-render.exe
conda-repo: C:\Users\a.muller\Anaconda3\Scripts\conda-repo.exe
conda-server: C:\Users\a.muller\Anaconda3\Scripts\conda-server.exe
conda-skeleton: C:\Users\a.muller\Anaconda3\Scripts\conda-skeleton.exe
conda-token: C:\Users\a.muller\Anaconda3\Scripts\conda-token.exe
conda-verify: C:\Users\a.muller\Anaconda3\Scripts\conda-verify.exe
user site dirs:

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: poliastro-main
CONDA_EXE: C:\Users\a.muller\Anaconda3\Scripts\conda.exe
CONDA_PREFIX: C:\Users\a.muller\Anaconda3\envs\poliastro-main
CONDA_PREFIX_1: C:\Users\a.muller\Anaconda3
CONDA_PROMPT_MODIFIER: (poliastro-main)
CONDA_PYTHON_EXE: C:\Users\a.muller\Anaconda3\python.exe
CONDA_ROOT: C:\Users\a.muller\Anaconda3
CONDA_SHLVL: 2
CURL_CA_BUNDLE: <not set>
HOMEPATH: \
PATH: C:\Users\a.muller\Anaconda3;C:\Users\a.muller\Anaconda3\Library\mingw-w64\bin;C:\Users\a.muller\Anaconda3\Library\usr\bin;C:\Users\a.muller\Anaconda3\Library\bin;C:\Users\a.muller\Anaconda3\Scripts;C:\Users\a.muller\Anaconda3\bin;C:\Users\a.muller\Anaconda3\envs\poliastro-main;C:\Users\a.muller\Anaconda3\envs\poliastro-main\Library\mingw-w64\bin;C:\Users\a.muller\Anaconda3\envs\poliastro-main\Library\usr\bin;C:\Users\a.muller\Anaconda3\envs\poliastro-main\Library\bin;C:\Users\a.muller\Anaconda3\envs\poliastro-main\Scripts;C:\Users\a.muller\Anaconda3\envs\poliastro-main\bin;C:\Users\a.muller\Anaconda3\condabin;C:\Python365\Scripts;C:\Python365;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;C:\windows\System32\OpenSSH;C:\Users\a.muller\AppData\Local\Microsoft\WindowsApps;C:\Users\a.muller\AppData\Local\JetBrains\PyCharm 2022.1\bin;.;C:\Users\a.muller\AppData\Local\Programs\Git\cmd;C:\Users\a.muller\AppData\Local\GitHubDesktop\bin
PSMODULEPATH: D:\a.muller\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\WindowsPowerShell\v1.0\Modules
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>

```
</details>

<details>

<summary> conda list </summary>

```bash
(poliastro-main) PS C:\> conda list
# packages in environment at C:\Users\a.muller\Anaconda3\envs\poliastro-main:
#
# Name                    Version                   Build  Channel
astropy                   5.0.4                    pypi_0    pypi
astroquery                0.4.6                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
ca-certificates           2022.4.26            haa95532_0
certifi                   2021.10.8        py39haa95532_2
charset-normalizer        2.0.12                   pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
fonttools                 4.33.3                   pypi_0    pypi
git                       2.34.1               haa95532_0
html5lib                  1.1                      pypi_0    pypi
idna                      3.3                      pypi_0    pypi
importlib-metadata        4.11.3                   pypi_0    pypi
jpeg                      9e                   h2bbff1b_0
jplephem                  2.17                     pypi_0    pypi
keyring                   23.5.0                   pypi_0    pypi
kiwisolver                1.4.2                    pypi_0    pypi
libcurl                   7.82.0               h86230a5_0
libssh2                   1.10.0               hcd4344a_0
libtiff                   4.2.0                hd0e1b90_0
llvmlite                  0.38.0                   pypi_0    pypi
lz4-c                     1.9.3                h2bbff1b_1
matplotlib                3.5.2                    pypi_0    pypi
numba                     0.55.1                   pypi_0    pypi
numpy                     1.21.6                   pypi_0    pypi
openssl                   1.1.1o               h2bbff1b_0
packaging                 21.3                     pypi_0    pypi
pandas                    1.4.2                    pypi_0    pypi
pillow                    9.1.1                    pypi_0    pypi
pip                       21.2.4           py39haa95532_0
plotly                    5.8.0                    pypi_0    pypi
poliastro                 0.17.dev0                pypi_0    pypi
proj                      8.2.1                h5ed7ab8_0
pyerfa                    2.0.0.1                  pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyproj                    3.3.1                    pypi_0    pypi
python                    3.9.12               h6244533_0
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2022.1                   pypi_0    pypi
pyvo                      1.3                      pypi_0    pypi
pywin32-ctypes            0.2.0                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
requests                  2.27.1                   pypi_0    pypi
scipy                     1.8.1                    pypi_0    pypi
setuptools                61.2.0           py39haa95532_0
six                       1.16.0                   pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlite                    3.38.3               h2bbff1b_0
tenacity                  8.0.1                    pypi_0    pypi
tzdata                    2022a                hda174b7_0
urllib3                   1.26.9                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2              py39haa95532_2
xz                        5.2.5                h8cc25b3_1
zipp                      3.8.0                    pypi_0    pypi
zlib                      1.2.12               h8cc25b3_2
zstd                      1.4.9                h19a0ad4_0

```
</details>

<details>
<summary> pip freeze </summary>

```bash
(poliastro-main) PS C:\> pip freeze
astropy==5.0.4
astroquery==0.4.6
beautifulsoup4==4.11.1
certifi==2021.10.8
charset-normalizer==2.0.12
cycler==0.11.0
fonttools==4.33.3
html5lib==1.1
idna==3.3
importlib-metadata==4.11.3
jplephem==2.17
keyring==23.5.0
kiwisolver==1.4.2
llvmlite==0.38.0
matplotlib==3.5.2
numba==0.55.1
numpy==1.21.6
packaging==21.3
pandas==1.4.2
Pillow==9.1.1
plotly==5.8.0
poliastro @ git+https://github.com/poliastro/poliastro.git@968ac2c2b3050caabb1ef02ba5841029c96dd6aa
pyerfa==2.0.0.1
pyparsing==3.0.9
pyproj==3.3.1
python-dateutil==2.8.2
pytz==2022.1
pyvo==1.3
pywin32-ctypes==0.2.0
PyYAML==6.0
requests==2.27.1
scipy==1.8.1
six==1.16.0
soupsieve==2.3.2.post1
tenacity==8.0.1
urllib3==1.26.9
webencodings==0.5.1
wincertstore==0.2
zipp==3.8.0

```
</details>

**Comment by astrojuanlu** [comment] 2022-05-29 16:07
Just reproduced this in latest `main` :+1:

**Comment by astrojuanlu** [comment] 2022-05-29 16:16
The culprit is in the `period`, which appears to be too big and makes the list of `epochs` empty:

https://github.com/poliastro/poliastro/blob/968ac2c2b3050caabb1ef02ba5841029c96dd6aa/src/poliastro/ephem.py#L49-L55

```
ipdb> l
     51         end=Time(t_span[1], format="jd", scale="tdb"),
     52         periods=int(
     53             ((t_span[1] - t_span[0]) / (period * rtol)).to_value(u.one)
     54         ),
     55     )
---> 56     ephem = Ephem.from_body(body, epochs, attractor=attractor)
     57 
     58     interpolant = interp1d(
     59         (epochs - epochs[0]).to_value(u.s),
     60         ephem._coordinates.xyz.to_value(u.km),
     61     )

ipdb> p epochs
<Time object: scale='tdb' format='jd' value=[]>
ipdb> p t_span
(<Quantity 2458849.5 d>, <Quantity 2458850.5 d>)
ipdb> p int(((t_span[1] - t_span[0]) / (period * rtol)).to_value(u.one))
0
```

Picking a shorter period fixes the problem:

```
In [3]: Sun_r = build_ephem_interpolant(Sun, 1 * u.day,
   ...:                                 (start_epoch_Time_obj.to_value("jd") << u.d, end_epoch_Time_obj.to_value("jd") << u.d),
   ...:                                 rtol=1e-2)

In [4]: Sun_r
Out[4]: <scipy.interpolate._interpolate.interp1d at 0x7f9c589ad3b0>
```

This is my fault because I gave you ill advice at https://github.com/poliastro/poliastro/issues/1504#issuecomment-1130037566, which means that the `period` parameter is confusing even for me. We need to decide whether:

- Keep `period`, but clarify its docstring and produce a better error message if the resulting length is zero, or
- Use a different parameter, like "number of samples" or similar (or even requiring the user to use `poliastro.util.time_range`.

I hope that with the information above you can continue working @Nosudrum

**Comment by astrojuanlu** [comment] 2022-05-29 16:18
Notice that the bug happens for other bodies that are not the `Sun`:

```
In [8]: build_ephem_interpolant(Earth, 1 * u.year,
   ...:                                 (start_epoch_Time_obj.to_value("jd") << u.d, end_epoch_Time_obj.to_value("jd") << u.d),
   ...:                                 rtol=1e-2)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
...
```

**Comment by Nosudrum** [comment] 2022-05-30 07:41
So the `period` parameter is in fact not the orbital period of the body, but related to the sampling of the interpolant. Got it.

From my testing, with `rtol=1e-2` and a start/end epochs delta of `1 day`, the maximum value in whole days for the period is `50 days`. So basically the limit is that `rtol*period<=0.5*DeltaEpochs`, such that at least two entries can be generated for the interpolant, which makes sense.

I'll try to play a bit more with `rtol` and `period` to find an acceptable tradeoff between accuracy and speed in my usecase.

That's another issue solved, thanks for your help ! :)

**Comment by astrojuanlu** [comment] 2022-05-30 08:17
Glad it worked! I'm reopening this to keep track of the docs/parameter changes.

**Comment by astrojuanlu** [comment] 2022-07-20 09:14
Addressed by gh-1548, we refactored `build_ephem_interpolant` so that it receives the `epochs` directly. This is hopefully easier to understand, since the `poliastro.util.time_range` function is well documented.

Closing!

**Closed by astrojuanlu** 2022-07-20 09:14 UTC
Labels: triaging:enhancement
