### ISSUE TITLE
Error with ephemerides

### ISSUE THREAD

**Issue by Davide-sd** [poliastro/poliastro#147] opened 2017-02-17 20:32 UTC
Today I've install poliastro and I tryed to follow the example code in the documentation.
I'm having problem with the ephemerides. This is the error i get:

```---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-43-9c36e44cc7f8> in <module>()
      1 print(epoch)
----> 2 r, v = ephem.planet_ephem(ephem.EARTH, epoch)
      3 print(r)
      4 print(v)

/home/davide/anaconda3/lib/python3.6/site-packages/poliastro/ephem.py in planet_ephem(body, epoch, kernel)
    130 
    131     """
--> 132     r, v = kernel[0, body].compute_and_differentiate(epoch.jd1, epoch.jd2)
    133     r = r * u.km
    134     v = v * u.km / u.day

TypeError: 'NoneType' object is not subscriptable
```

Can anybody try the example [in the user guide](http://poliastro.readthedocs.io/en/latest/user_guide.html#where-are-the-planets-computing-ephemerides) and let me know if you replicate this error?

**Comment by Juanlu001** [comment] 2017-02-18 11:39
Hi @Davide-sd, thanks for the bug report! This is a duplicate of #128, now that you're the second person to report it I'm trying to fix it ASAP. Please subscribe there for upcoming updates, I might release a 0.6.1 with the fix.

**Closed by Juanlu001** 2017-02-18 11:39 UTC
