### ISSUE TITLE
AttributeError: 'Orbit' object has no attribute 'frame'

### ISSUE THREAD

**Issue by iamabhishek0** [poliastro/poliastro#849] opened 2020-02-26 18:01 UTC
```
>>> from poliastro import *
>>> r = [-6045, -3490, 2500] * u.km
>>> v = [-3.457, 6.618, 2.533] * u.km / u.s
>>> ss = Orbit.from_vectors(Earth, r, v)
>>> ss
7283 x 10293 km x 153.2 deg (GCRS) orbit around Earth (♁) at epoch J2000.000 (TT)
>>> ss.frame
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Orbit' object has no attribute 'frame'
```

**Comment by Juanlu001** [comment] 2020-02-27 23:07
Hi @iamabhishek0, I tried this with `master` and everything worked:

```
>>> from astropy import units as u
>>> r = [-6045, -3490, 2500] * u.km
>>> v = [-3.457, 6.618, 2.533] * u.km / u.s
>>> from poliastro.twobody import Orbit
>>> from poliastro.bodies import Earth
>>> ss = Orbit.from_vectors(Earth, r, v)
>>> ss.frame
<GCRS Frame (obstime=J2000.000, obsgeoloc=(0., 0., 0.) m, obsgeovel=(0., 0., 0.) m / s)>
```

could you please tell us what poliastro version are you using?

**Comment by iamabhishek0** [comment] 2020-02-28 17:57
I am using the current version which is on the master.

**Comment by Juanlu001** [comment] 2020-03-03 16:03
I am not at all sure. Are you using Linux? Could you please paste the output of

```
$ which python
$ python -m pip list | grep poliastro
$ python -c "from poliastro.examples import iss; print(iss.frame)"
```

?

**Comment by iamabhishek0** [comment] 2020-03-03 16:36
Yes, I am using Linux.
```
(polienv) [uchiha@pop-os src{master}]$ which python
/home/uchiha/Desktop/poliastro/polienv/bin/python
(polienv) [uchiha@pop-os src{master}]$ python -m pip list | grep poliastro
(polienv) [uchiha@pop-os src{master}]$ python -c "from poliastro.examples import iss; print(iss.frame)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'Orbit' object has no attribute 'frame'
```

**Comment by Juanlu001** [comment] 2020-03-03 16:41
Well, `python -m pip list` doesn't find it, so I wonder where is it finding it.

Can you do this?

```
$ python -c "import poliastro as p; print(p.__file__)"
$ python -c "import poliastro as p; print(p.__version__)"
```

**Comment by iamabhishek0** [comment] 2020-03-03 16:42
```
(polienv) [uchiha@pop-os src{master}]$ python -c "import poliastro as p; print(p.__file__)"
/home/uchiha/Desktop/poliastro/src/poliastro/__init__.py
(polienv) [uchiha@pop-os src{master}]$ python -c "import poliastro as p; print(p.__version__)"
0.14.post0.dev0

```

**Comment by Juanlu001** [comment] 2020-03-03 16:45
Okay, so you're running the code inside `src/poliastro`. You won't need to do that if you `flit install --symlink` where `pyproject.toml` is, but let's not get there yet.

Last thing: do `git status`, since unfortunately the `__version__` does not record the commit...

**Comment by iamabhishek0** [comment] 2020-03-03 16:49
```
(polienv) [uchiha@pop-os src{master}]$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        ../polienv/

nothing added to commit but untracked files present (use "git add" to track)

```

**Comment by Juanlu001** [comment] 2020-03-03 16:54
Sorry, I forgot the most important one :man_facepalming: `git show`

**Comment by iamabhishek0** [comment] 2020-03-03 16:56
```
(polienv) [uchiha@pop-os src{master}]$ git show
commit 9994fd6a8e939ac74e0385232b689c46aa59a906 (HEAD -> master, origin/master, origin/HEAD)
Merge: 77b2f9f 5224680
Author: Juan Luis Cano Rodríguez <hello@juanlu.space>
Date:   Tue Mar 3 17:01:49 2020 +0100

    Merge pull request #853 from iamabhishek0/fixes_#852
    
    Fixed Broken benchmarks Link

```

**Comment by iamabhishek0** [comment] 2020-03-03 17:02
Actually when I was setting up my virtual environment I did `pip install .`
But then I had to work on python 3.7.4 which was giving segmentation fault because of numba's bug.
So I created virtual environment using `python3 -m virtualenv polienv` and installed all the dependencies manually after which everything was working fine.
Sorry for installing the dependencies this way because I wasn't aware of `flit install --symlink`, I will give it a try today.

**Comment by Juanlu001** [comment] 2020-03-03 17:30
All right, sorry for the loooooooooong delay. I reproduced the "issue", now let me remember if it's actually a bug or a feature.

**Comment by Juanlu001** [comment] 2020-03-03 17:32
This change was introduced in https://github.com/poliastro/poliastro/pull/827 and now the equivalent thing is to do `ss.get_frame()`.

If you saw `ss.frame` in any place of the documentation then this is a bug, otherwise let's close it.

**Comment by iamabhishek0** [comment] 2020-03-03 19:16
@Juanlu001 Thank for your support, We could close this one after fixing the documentation.

**Closed** 2020-03-03 23:06 UTC
Labels: support
