### ISSUE TITLE
check units on Body / State instantiation

### ISSUE THREAD

**Issue by bryan-lunt** [poliastro/poliastro#96] opened 2016-01-03 20:12 UTC
Currently if you instantiate a body with the gravitational parameter in m^3/s^2 (some) results later in the program become nonsense.
I humbly propose it would be nice to either check that the units are km^3/s^2 when instantiating  body, throwing an exception if they are not, or better yet, to convert them to the appropriate unit.

**Comment by Juanlu001** [comment] 2016-01-04 06:58
Hello @bryan-lunt, thanks for the suggestion! However, a check like that is already in place in the library: https://github.com/poliastro/poliastro/blob/4a5692bcc10b96a4ab5e86ba02e43bd1d9bb572b/src/poliastro/bodies.py#L39 did you mean something else?

**Comment by Juanlu001** [comment] 2016-01-04 07:00
Sorry, I read only the second half of your comment.

If I understand correctly, the problem is that when using m^3/s^2 the units don't cancel out automatically and that strange combinations appear, right? Can you post a specific code sample?

**Comment by Juanlu001** [comment] 2016-03-02 19:29
I was not able to reproduce this behavior, and after fixing #110 perhaps it disappeared. I will close the issue but feel free to reopen if you can provide a code snippet that triggers the problem.

**Closed by Juanlu001** 2016-03-02 19:29 UTC
Labels: 1 - Ready, easy, enhancement
