### ISSUE TITLE
AssertionError in izzo library

### ISSUE THREAD

**Issue by Tarlan0001** [poliastro/poliastro#492] opened 2018-11-14 16:21 UTC
I got the following:
``` 
(f_v0, f_v), = izzo.lambert(Earth_k, r0, r, tof)
File "c:\users\...\site-packages\poliastro\iod\izzo.py", line 44, in lambert
    for v0, v in sols:
AssertionError
```
I printed the variables: `r0=<Quantity [-4396.85721438,  2117.6460576 ,  4400.14349892] km>`, `r=<Quantity [ 4732.15467662, -2279.13443768, -4735.69156808] km>`, `tof= 30.0 min`

Where is the issue?

**Comment by Juanlu001** [comment] 2018-11-14 19:41
Hi @Tarlan0001, thanks for your interest in poliastro! I will take a look and see what's going on, but in any case a better error should be returned.

**Comment by Juanlu001** [comment] 2018-11-14 19:50
Unfortunately I could not reproduce the issue:

```
from poliastro.bodies import Earth
from astropy import units as u
from poliastro.iod import izzo

r0 = [-4396.85721438, 2117.6460576 , 4400.14349892] * u.km
r = [ 4732.15467662, -2279.13443768, -4735.69156808]  *u.km
tof = 30 * u.min
(f_v0, f_v), = izzo.lambert(Earth.k, r0, r, tof)
print(f_v0)
print(f_v)
```

Result:

```
$ python /tmp/izzo.py 
[-1.77393825 -7.89553974 -2.80865135] km / s
[ 5.82836646  5.32284027 -1.57360116] km / s
```

Can you please give some more details about your environment? conda or pip, versions of numpy, numba and scipy, operative system, python version.

**Comment by Tarlan0001** [comment] 2018-11-14 19:57
Try this (the values for `r0` and `r` would be the same, strangely):

```
def keplerian2cartesian(kepler):

    a=(kepler[0]+kepler[1]+Req*2)*1000/2
    e=(kepler[0]-kepler[1])/(kepler[0]+kepler[1]+Req*2)
    i=kepler[2]
    OMEGA=kepler[3]
    omega=kepler[4]
    tetta=kepler[5]

    gamma=math.atan((e*math.sin(tetta))/(1+e*math.cos(tetta)))
  
    r=(a*(1-e**2))/(1+e*math.cos(tetta))
    v=math.sqrt(Earth_k.value*(2/r-1/a))
   
    X=r*( math.cos(tetta+omega)*math.cos(OMEGA) - math.sin(tetta+omega)*math.cos(i)*math.sin(OMEGA) )
    Y=r*( math.cos(tetta+omega)*math.sin(OMEGA) + math.sin(tetta+omega)*math.cos(i)*math.cos(OMEGA) )
    Z=r*( math.sin(tetta+omega)*math.sin(i) )
  
    Vx=v*( -math.sin(tetta+omega-gamma)*math.cos(OMEGA) - math.cos(tetta+omega-gamma)*math.cos(i)*math.sin(OMEGA) )
    Vy=v*( -math.sin(tetta+omega-gamma)*math.sin(OMEGA) + math.cos(tetta+omega-gamma)*math.cos(i)*math.cos(OMEGA) )
    Vz=v*(  math.cos(tetta+omega-gamma)*math.sin(i) )
  
    return [X/1000,Y/1000,Z/1000,Vx/1000,Vy/1000,Vz/1000]

kepler0=[200,  200, 64.3*math.pi/180, 0, 310*math.pi/180]
kepler=[8000, 700, 64.3*math.pi/180, 0, 310*math.pi/180]

vector0=keplerian2cartesian(kepler0 + [182*math.pi/180])
vector=keplerian2cartesian(kepler + [2*math.pi/180])

r0 =vector0[0:3]  * u.km
r =vector[0:3]  * u.km

tof=30 * u.min
(f_v0, f_v), = izzo.lambert(Earth.k, r0, r, tof)

```

**Comment by Juanlu001** [comment] 2018-11-14 20:06
I assume `Req = Earth.R.to(u.km).value`. I run this code and still no problems.

> Can you please give some more details about your environment? conda or pip, versions of numpy, numba and scipy, operative system, python version.

**Comment by Juanlu001** [comment] 2018-11-14 20:09
Also, notice that you don't have to write `keplerian2cartesian` yourself, as there is `poliastro.core.elements.coe2rv` https://docs.poliastro.space/en/latest/core.html#poliastro.core.elements.coe2rv.

**Comment by Tarlan0001** [comment] 2018-11-14 20:10
`Req=6371`

**Comment by Juanlu001** [comment] 2018-11-14 20:11
Okay, with this value I could reproduce. Working on it.

**Comment by Tarlan0001** [comment] 2018-11-14 20:17
This code worked with `Req = Earth.R.to(u.km).value` worked.

However, If I replace 
```
vector0=keplerian2cartesian(kepler0 + [182*math.pi/180])
vector=keplerian2cartesian(kepler + [2*math.pi/180])
```
by
```
vector0=keplerian2cartesian(kepler0 + [181*math.pi/180])
vector=keplerian2cartesian(kepler + [1*math.pi/180])
```

It would gave the error. Why?

**Comment by Juanlu001** [comment] 2018-11-14 20:19
Disabling the JIT and exposing the floating point errors I got this:

```
---------------------------------------------------------------------------
FloatingPointError                        Traceback (most recent call last)
<ipython-input-7-ecb4e84c5994> in <module>()
     33 
     34 tof=30 * u.min
---> 35 (f_v0, f_v), = izzo.lambert(Earth.k, r0, r, tof)

~/.miniconda36/envs/poliastro37/lib/python3.7/site-packages/poliastro/iod/izzo.py in lambert(k, r0, r, tof, M, numiter, rtol)
     42     sols = izzo_fast(k_, r0_, r_, tof_, M, numiter, rtol)
     43 
---> 44     for v0, v in sols:
     45         yield v0 * u.km / u.s, v * u.km / u.s

~/.miniconda36/envs/poliastro37/lib/python3.7/site-packages/poliastro/core/iod.py in izzo(k, r1, r2, tof, M, numiter, rtol)
     91 
     92     # Geometry of the problem
---> 93     ll = np.sqrt(1 - c_norm / s)
     94 
     95     if i_h[2] < 0:

FloatingPointError: invalid value encountered in sqrt

In [8]: %debug
> /home/juanlu/.miniconda36/envs/poliastro37/lib/python3.7/site-packages/poliastro/core/iod.py(93)izzo()
     91 
     92     # Geometry of the problem
---> 93     ll = np.sqrt(1 - c_norm / s)
     94 
     95     if i_h[2] < 0:

ipdb> p c_norm
13643.094194541876
ipdb> p s
13643.094194541874
ipdb> p 1 - c_norm / s
-2.220446049250313e-16
```

So it seems that there's some weird condition in which an internal rounding error makes the square root fail.

**Comment by Tarlan0001** [comment] 2018-11-14 20:20
How could I solve this?

**Comment by Juanlu001** [comment] 2018-11-14 20:30
I discard the geometry issue, because running with `Req = 6370` succeeds, `6371` fails, and `6378` succeeds again. The resulting orbits have nothing special (an eccentricity of 0.425, so not even hyperbolic).

**Comment by Juanlu001** [comment] 2018-11-14 20:33
@Tarlan0001 this change fixes the issue and makes sense from a mathematical point of view:

```
diff --git a/src/poliastro/core/iod.py b/src/poliastro/core/iod.py
index f5d54a6..9fa5222 100644
--- a/src/poliastro/core/iod.py
+++ b/src/poliastro/core/iod.py
@@ -90,7 +90,9 @@ def izzo(k, r1, r2, tof, M, numiter, rtol):
     i_h = i_h / norm(i_h)  # Fixed from paper
 
     # Geometry of the problem
-    ll = np.sqrt(1 - c_norm / s)
+    # We use min(1.0, c_norm / s) because the chord cannot be larger than the
+    # semiperimeter, except for rounding errors
+    ll = np.sqrt(1 - min(1.0, c_norm / s))
 
     if i_h[2] < 0:
         ll = -ll
```

Do you want to make a pull request?

**Comment by Tarlan0001** [comment] 2018-11-14 20:35
I'm using pip. May I download this?

**Comment by Juanlu001** [comment] 2018-11-14 20:37
If you want a fix right now, you can edit the `poliastro/core/iod.py` in your computer. If you can wait some days, when someone (perhaps me) makes a pull request with a proper test, it will be merged to the `master` branch and you will be able to install it directly from there. And if you can wait some weeks, I assume 0.11.1 will have this issue fixed.

**Comment by Tarlan0001** [comment] 2018-11-14 20:39
Thanks!

**Comment by Juanlu001** [comment] 2018-11-14 21:05
Reopening, because this still needs fixing.

**Comment by Tarlan0001** [comment] 2018-11-14 21:33
A little off-topic, but related to the Lambert problem:
I'm trying to calculate the optimal trajectory from one orbit to another. For that, I'm calculating lambert function for initial and final orbit true anomaly in an interval [0,360] and transfer time [30,10*24*60]. Is this fine?

I'm using a single revolution because don't understand the multiple revolution approach. The question is asked on stackexchange: https://space.stackexchange.com/questions/31967/multiple-revolution-lambert-problem

**Comment by Juanlu001** [comment] 2018-11-15 08:17
> I'm trying to calculate the optimal trajectory from one orbit to another. For that, I'm calculating lambert function for initial and final orbit true anomaly in an interval [0,360] and transfer time [30,10* 24* 60]. Is this fine?

Sure! Although you would also benefit from using the multirevolution case.

A common tool used in these kind of problems is Porkchop plots. We were considering adding one to poliastro (https://github.com/poliastro/poliastro/issues/156), and I think @IngenieroDeAviones was interested in pushing that forward.

> I'm using a single revolution because don't understand the multiple revolution approach. The question is asked on stackexchange.

I will answer there (so I might gain some points :wink:) but I commit to adding that to the documentation as well (https://github.com/poliastro/poliastro/issues/494).

**Comment by Juanlu001** [comment] 2018-11-15 11:17
Interested readers: I posted an answer, please upvote! https://space.stackexchange.com/a/32020/10716

**Comment by Tarlan0001** [comment] 2018-11-15 15:05
I got a "Division by zero" error in the same place...

```
from astropy import units as u
from poliastro.bodies import Earth
from poliastro.iod import izzo
import math
import time

Earth_k = Earth.k
Req = Earth.R.to(u.km).value

def keplerian2cartesian(kepler):

    a=(kepler[0]+kepler[1]+Req*2)*1000/2
    e=(kepler[0]-kepler[1])/(kepler[0]+kepler[1]+Req*2)
    i=kepler[2]
    OMEGA=kepler[3]
    omega=kepler[4]
    tetta=kepler[5]

    gamma=math.atan((e*math.sin(tetta))/(1+e*math.cos(tetta)))
  
    r=(a*(1-e**2))/(1+e*math.cos(tetta))
    v=math.sqrt(Earth.k.value*(2/r-1/a))
   
    X=r*( math.cos(tetta+omega)*math.cos(OMEGA) - math.sin(tetta+omega)*math.cos(i)*math.sin(OMEGA) )
    Y=r*( math.cos(tetta+omega)*math.sin(OMEGA) + math.sin(tetta+omega)*math.cos(i)*math.cos(OMEGA) )
    Z=r*( math.sin(tetta+omega)*math.sin(i) )
  
    Vx=v*( -math.sin(tetta+omega-gamma)*math.cos(OMEGA) - math.cos(tetta+omega-gamma)*math.cos(i)*math.sin(OMEGA) )
    Vy=v*( -math.sin(tetta+omega-gamma)*math.sin(OMEGA) + math.cos(tetta+omega-gamma)*math.cos(i)*math.cos(OMEGA) )
    Vz=v*(  math.cos(tetta+omega-gamma)*math.sin(i) )
  
    return [X/1000,Y/1000,Z/1000,Vx/1000,Vy/1000,Vz/1000]

kepler0=[800,  800,  80*math.pi/180, 0, 310*math.pi/180,0]
kepler=[2000, 800, 80*math.pi/180, 0, 310*math.pi/180,0]

vector0=keplerian2cartesian(kepler0)
vector=keplerian2cartesian(kepler)

r0 =vector0[0:3]  * u.km
r =vector[0:3]  * u.km

tof=30 * u.min
(f_v0, f_v), = izzo.lambert(Earth.k, r0, r, tof)
```

**Comment by Juanlu001** [comment] 2018-11-15 15:11
Of course, because the vectors are parallel and therefore the Lambert solution cannot be computed:

```
In [10]: r0
Out[10]: <Quantity [ 4614.01726712,  -954.85167719, -5415.23295728] km>

In [11]: r
Out[11]: <Quantity [ 4614.01726712,  -954.85167719, -5415.23295728] km>

In [12]: np.cross(r0, r)
Out[12]: array([0., 0., 0.])
```

**Comment by Tarlan0001** [comment] 2018-11-15 17:39
But that shouldn't give an error. I'm transferring between 2 coplanar orbits, one on 800km perigee and apogee, and other on 800km perigee and 2000 apogee.
In this case, probably, the first deltaV is 0 (as perigees are same), and the second impulse raises the apogee...

**Comment by Juanlu001** [comment] 2018-11-15 18:55
If you already know that the orbits are coplanar and tangential, you should use the Hohmann maneuver instead:

https://docs.poliastro.space/en/latest/user_guide.html#changing-the-orbit-maneuver-objects

The Lambert problem is only useful when you know the initial position vector, the final position vector, the time of flight, and they are not collinear. If the vectors are collinear, infinite solutions for the two-body boundary value problem exist and it cannot be solved.

**Comment by Tarlan0001** [comment] 2018-11-15 20:34
I can't use Hohmann transfer, because the second orbit is not circular.
If the perigees are the same, is it OK just to find the difference in velocities on perigee as a DV?

**Comment by Juanlu001** [comment] 2018-11-16 17:10
> Or you mean, to take into account only first impulse?

That would be one possibility. In Hohmann, the intermediate transfer orbit is not circular either.

> If the perigees are the same, is it OK just to find the difference in velocities on perigee as a DV?

Yes!

**Comment by Juanlu001** [comment] 2018-12-09 06:51
These issues will be fixed in the next poliastro release. Thanks for reporting!

**Closed** 2018-12-09 06:50 UTC
Labels: bug, support
