### ISSUE TITLE
Binder Doesn't work

### ISSUE THREAD

**Issue by shreyasbapat** [poliastro/poliastro#360] opened 2018-04-25 09:16 UTC
🐞 **Problem**

The binder tab given in the docs : http://docs.poliastro.space/en/latest/ Doesn't seem to work as expected. It says "Error loading poliastro/poliastro/master!"
![screenshot-2018-4-25 binder beta](https://user-images.githubusercontent.com/24257914/39236874-93958dde-4897-11e8-9a9c-424e67556cb5.png)

🖥 **Please paste the output of following commands**

`conda info -a`

`python -c "import poliastro.testing; poliastro.testing.test()"`

🎯 **Goal**

💡 **Possible solutions**

📋  **Steps to solve the problem**

 * Comment below about what you've started working on.
 * Add, commit, push your changes
 * Submit a pull request and add this in comments - `Addresses #<put issue number here>`
 * Ask for a review in comments section of pull request
 * Celebrate your contribution to this project 🎉

**Comment by Juanlu001** [comment] 2018-04-25 09:49
Thanks for the timely bug report @shreyasbapat! I could reproduce it on the first attempt. Apparently some sorts of network problems plus a messed up, patched pip can lead to this error:

https://stackoverflow.com/q/37495375/554319
https://github.com/pypa/pip/issues/4779
https://github.com/pypa/pip/issues/3943

I'm trying to reload the build in case it's a temporary problem.

**Comment by Juanlu001** [comment] 2018-04-25 09:52
I asked the devs in https://gitter.im/jupyterhub/binder

**Comment by Juanlu001** [comment] 2018-04-25 09:54
Indeed these were temporary problems. Now the build is broken because of https://github.com/numba/numba/issues/2917:

![screenshot-2018-4-25 binder beta](https://user-images.githubusercontent.com/316517/39238716-4458c8fc-487f-11e8-8144-175f743fe73d.png)

I will close this as "not our problem". Although I admit that the error is quite ugly...

**Closed by Juanlu001** 2018-04-25 09:54 UTC

**Comment by shreyasbapat** [comment] 2018-04-25 09:57
Yes! True!

**Comment by Juanlu001** [comment] 2018-04-25 13:30
I think this might be related: https://status.python.org/incidents/4pb9smlrpt3k
