### ISSUE TITLE
ImportError: cannot import name 'solve_ivp'

### ISSUE THREAD

**Issue by PabloRdrRbl** [poliastro/poliastro#433] opened 2018-08-10 16:50 UTC
On Mac OS X 10.11.6, after creating a new condo environment with Python 3.6 and running

`conda install poliastro --channel conda-forge`

I get the following error: ImportError: cannot import name 'solve_ivp'.

Here the output for the different commands:

`conda info -a`

```
Current conda install:

               platform : osx-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.18.4
       root environment : /Users/pablo/miniconda3  (writable)
    default environment : /Users/pablo/miniconda3/envs/poliastro
       envs directories : /Users/pablo/miniconda3/envs
                          /Users/pablo/.conda/envs
          package cache : /Users/pablo/miniconda3/pkgs
                          /Users/pablo/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.18.4 CPython/3.6.1 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20
# conda environments:
#
poliastro             *  /Users/pablo/miniconda3/envs/poliastro
poliastro_env            /Users/pablo/miniconda3/envs/poliastro_env
python2                  /Users/pablo/miniconda3/envs/python2
python3                  /Users/pablo/miniconda3/envs/python3
root                     /Users/pablo/miniconda3

sys.version: 3.6.1 |Continuum Analytics, Inc.| (defau...
sys.prefix: /Users/pablo/miniconda3
sys.executable: /Users/pablo/miniconda3/bin/python
conda location: /Users/pablo/miniconda3/lib/python3.6/site-packages/conda
conda-build: None
conda-env: /Users/pablo/miniconda3/bin/conda-env
user site dirs: ~/.local/lib/python3.6

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: poliastro
CONDA_ENVS_PATH: <not set>
DYLD_LIBRARY_PATH: <not set>
PATH: /Users/pablo/miniconda3/envs/poliastro/bin:/usr/local/bin:/Users/pablo/miniconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin
PYTHONHOME: <not set>
PYTHONPATH: <not set>

WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license
```

`python -c "import poliastro.testing; poliastro.testing.test()"`

```
platform darwin -- Python 3.6.2, pytest-3.7.1, py-1.5.4, pluggy-0.7.1
rootdir: /Users/pablo, inifile:
plugins: remotedata-0.3.0, openfiles-0.3.0, doctestplus-0.1.3, arraydiff-0.2
collected 37 items / 18 errors

==================================== ERRORS ====================================
 ERROR collecting miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_coordinates.py
ImportError while importing test module '/Users/pablo/miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_coordinates.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_coordinates.py:6: in <module>
    from poliastro import coordinates, bodies
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/coordinates.py:16: in <module>
    from poliastro.twobody.orbit import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/__init__.py:1: in <module>
    from poliastro.twobody.orbit import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/orbit.py:13: in <module>
    from poliastro.twobody.propagation import propagate, mean_motion, cowell
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/propagation.py:7: in <module>
    from scipy.integrate import solve_ivp
E   ImportError: cannot import name 'solve_ivp'
 ERROR collecting miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_examples.py
ImportError while importing test module '/Users/pablo/miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_examples.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_examples.py:2: in <module>
    from poliastro import examples
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/examples.py:8: in <module>
    from poliastro.twobody import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/__init__.py:1: in <module>
    from poliastro.twobody.orbit import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/orbit.py:13: in <module>
    from poliastro.twobody.propagation import propagate, mean_motion, cowell
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/propagation.py:7: in <module>
    from scipy.integrate import solve_ivp
E   ImportError: cannot import name 'solve_ivp'
 ERROR collecting miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_maneuver.py
ImportError while importing test module '/Users/pablo/miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_maneuver.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_maneuver.py:10: in <module>
    from poliastro.twobody import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/__init__.py:1: in <module>
    from poliastro.twobody.orbit import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/orbit.py:13: in <module>
    from poliastro.twobody.propagation import propagate, mean_motion, cowell
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/propagation.py:7: in <module>
    from scipy.integrate import solve_ivp
E   ImportError: cannot import name 'solve_ivp'
 ERROR collecting miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_patched_conics.py
ImportError while importing test module '/Users/pablo/miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_patched_conics.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_patched_conics.py:11: in <module>
    from poliastro.patched_conics import compute_soi
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/patched_conics.py:9: in <module>
    from poliastro.twobody import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/__init__.py:1: in <module>
    from poliastro.twobody.orbit import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/orbit.py:13: in <module>
    from poliastro.twobody.propagation import propagate, mean_motion, cowell
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/propagation.py:7: in <module>
    from scipy.integrate import solve_ivp
E   ImportError: cannot import name 'solve_ivp'
 ERROR collecting miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_plotting.py
ImportError while importing test module '/Users/pablo/miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_plotting.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_plotting.py:7: in <module>
    from poliastro.examples import iss
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/examples.py:8: in <module>
    from poliastro.twobody import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/__init__.py:1: in <module>
    from poliastro.twobody.orbit import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/orbit.py:13: in <module>
    from poliastro.twobody.propagation import propagate, mean_motion, cowell
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/propagation.py:7: in <module>
    from scipy.integrate import solve_ivp
E   ImportError: cannot import name 'solve_ivp'
 ERROR collecting miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_plotting2d.py
ImportError while importing test module '/Users/pablo/miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_plotting2d.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_plotting2d.py:9: in <module>
    from poliastro.examples import iss
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/examples.py:8: in <module>
    from poliastro.twobody import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/__init__.py:1: in <module>
    from poliastro.twobody.orbit import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/orbit.py:13: in <module>
    from poliastro.twobody.propagation import propagate, mean_motion, cowell
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/propagation.py:7: in <module>
    from scipy.integrate import solve_ivp
E   ImportError: cannot import name 'solve_ivp'
 ERROR collecting miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_plotting3d.py
ImportError while importing test module '/Users/pablo/miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_plotting3d.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_plotting3d.py:9: in <module>
    from poliastro.examples import iss
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/examples.py:8: in <module>
    from poliastro.twobody import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/__init__.py:1: in <module>
    from poliastro.twobody.orbit import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/orbit.py:13: in <module>
    from poliastro.twobody.propagation import propagate, mean_motion, cowell
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/propagation.py:7: in <module>
    from scipy.integrate import solve_ivp
E   ImportError: cannot import name 'solve_ivp'
 ERROR collecting miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_twobody.py
ImportError while importing test module '/Users/pablo/miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_twobody.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/test_twobody.py:9: in <module>
    from poliastro.twobody.equinoctial import mee2coe
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/__init__.py:1: in <module>
    from poliastro.twobody.orbit import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/orbit.py:13: in <module>
    from poliastro.twobody.propagation import propagate, mean_motion, cowell
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/propagation.py:7: in <module>
    from scipy.integrate import solve_ivp
E   ImportError: cannot import name 'solve_ivp'
 ERROR collecting miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_neos/test_dastcom5.py
ImportError while importing test module '/Users/pablo/miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_neos/test_dastcom5.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_neos/test_dastcom5.py:6: in <module>
    from poliastro.examples import iss
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/examples.py:8: in <module>
    from poliastro.twobody import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/__init__.py:1: in <module>
    from poliastro.twobody.orbit import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/orbit.py:13: in <module>
    from poliastro.twobody.propagation import propagate, mean_motion, cowell
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/propagation.py:7: in <module>
    from scipy.integrate import solve_ivp
E   ImportError: cannot import name 'solve_ivp'
 ERROR collecting miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_neos/test_neos_neows.py
ImportError while importing test module '/Users/pablo/miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_neos/test_neos_neows.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_neos/test_neos_neows.py:8: in <module>
    from poliastro.neos import neows
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/neos/__init__.py:13: in <module>
    from poliastro.neos import neows, dastcom5
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/neos/neows.py:12: in <module>
    from poliastro.twobody.orbit import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/__init__.py:1: in <module>
    from poliastro.twobody.orbit import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/orbit.py:13: in <module>
    from poliastro.twobody.propagation import propagate, mean_motion, cowell
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/propagation.py:7: in <module>
    from scipy.integrate import solve_ivp
E   ImportError: cannot import name 'solve_ivp'
 ERROR collecting miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_angles.py
ImportError while importing test module '/Users/pablo/miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_angles.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_angles.py:7: in <module>
    from poliastro.twobody import angles
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/__init__.py:1: in <module>
    from poliastro.twobody.orbit import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/orbit.py:13: in <module>
    from poliastro.twobody.propagation import propagate, mean_motion, cowell
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/propagation.py:7: in <module>
    from scipy.integrate import solve_ivp
E   ImportError: cannot import name 'solve_ivp'
 ERROR collecting miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_decorators.py
ImportError while importing test module '/Users/pablo/miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_decorators.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_decorators.py:5: in <module>
    from poliastro.twobody.decorators import state_from_vector
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/__init__.py:1: in <module>
    from poliastro.twobody.orbit import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/orbit.py:13: in <module>
    from poliastro.twobody.propagation import propagate, mean_motion, cowell
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/propagation.py:7: in <module>
    from scipy.integrate import solve_ivp
E   ImportError: cannot import name 'solve_ivp'
 ERROR collecting miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_orbit.py
ImportError while importing test module '/Users/pablo/miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_orbit.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_orbit.py:14: in <module>
    from poliastro.twobody import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/__init__.py:1: in <module>
    from poliastro.twobody.orbit import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/orbit.py:13: in <module>
    from poliastro.twobody.propagation import propagate, mean_motion, cowell
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/propagation.py:7: in <module>
    from scipy.integrate import solve_ivp
E   ImportError: cannot import name 'solve_ivp'
 ERROR collecting miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_perturbations.py
ImportError while importing test module '/Users/pablo/miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_perturbations.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_perturbations.py:11: in <module>
    from poliastro.twobody.propagation import cowell
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/__init__.py:1: in <module>
    from poliastro.twobody.orbit import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/orbit.py:13: in <module>
    from poliastro.twobody.propagation import propagate, mean_motion, cowell
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/propagation.py:7: in <module>
    from scipy.integrate import solve_ivp
E   ImportError: cannot import name 'solve_ivp'
 ERROR collecting miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_propagation.py
ImportError while importing test module '/Users/pablo/miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_propagation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_propagation.py:14: in <module>
    from poliastro.twobody import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/__init__.py:1: in <module>
    from poliastro.twobody.orbit import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/orbit.py:13: in <module>
    from poliastro.twobody.propagation import propagate, mean_motion, cowell
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/propagation.py:7: in <module>
    from scipy.integrate import solve_ivp
E   ImportError: cannot import name 'solve_ivp'
 ERROR collecting miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_sample.py
ImportError while importing test module '/Users/pablo/miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_sample.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_sample.py:9: in <module>
    from poliastro.twobody import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/__init__.py:1: in <module>
    from poliastro.twobody.orbit import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/orbit.py:13: in <module>
    from poliastro.twobody.propagation import propagate, mean_motion, cowell
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/propagation.py:7: in <module>
    from scipy.integrate import solve_ivp
E   ImportError: cannot import name 'solve_ivp'
 ERROR collecting miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_states.py
ImportError while importing test module '/Users/pablo/miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_states.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_states.py:8: in <module>
    from poliastro.twobody.rv import RVState
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/__init__.py:1: in <module>
    from poliastro.twobody.orbit import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/orbit.py:13: in <module>
    from poliastro.twobody.propagation import propagate, mean_motion, cowell
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/propagation.py:7: in <module>
    from scipy.integrate import solve_ivp
E   ImportError: cannot import name 'solve_ivp'
 ERROR collecting miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_thrust.py
ImportError while importing test module '/Users/pablo/miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_thrust.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/tests/tests_twobody/test_thrust.py:9: in <module>
    from poliastro.twobody import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/__init__.py:1: in <module>
    from poliastro.twobody.orbit import Orbit
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/orbit.py:13: in <module>
    from poliastro.twobody.propagation import propagate, mean_motion, cowell
miniconda3/envs/poliastro/lib/python3.6/site-packages/poliastro/twobody/propagation.py:7: in <module>
    from scipy.integrate import solve_ivp
E   ImportError: cannot import name 'solve_ivp'
!!!!!!!!!!!!!!!!!!! Interrupted: 18 errors during collection !!!!!!!!!!!!!!!!!!!
=========================== 18 error in 2.46 seconds ===========================
```

`pip freeze | grep astropy`

```
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
astropy==3.0.4
pytest-astropy==0.4.0
```

`pip freeze | grep poliastro`

```
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
poliastro==0.10.0
```

**Comment by PabloRdrRbl** [comment] 2018-08-10 17:00
Somehow conda was not able of updating Scipy from 0.19.1 to 1.1. Solved after `conda install -c anaconda scipy`.

**Comment by Juanlu001** [comment] 2018-08-17 18:05
I suspect the original issue was caused by an old broken conda package https://github.com/conda-forge/poliastro-feedstock/issues/22 so I'm closing to track the conversation there. Thanks a lot @PabloRdrRbl!

**Closed by Juanlu001** 2018-08-17 18:05 UTC
