### ISSUE TITLE
Sampling error in tests

### ISSUE THREAD

**Issue by Yash-10** [poliastro/poliastro#1132] opened 2021-03-21 14:01 UTC
🐞 **Problem**

I have recently started to get a weird error after running `pytest`.

**Traceback**
```
============================================================================== FAILURES ==============================================================================
___________________________________________ test_sample_closed_starts_and_ends_at_min_anomaly_if_in_range_and_no_max_given ___________________________________________

>   ???

tests/tests_twobody/test_sampling.py:53: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/tests_twobody/test_sampling.py:68: in test_sample_closed_starts_and_ends_at_min_anomaly_if_in_range_and_no_max_given
    assert_quantity_allclose(result[-1], min_nu, atol=1e-14 * u.rad)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

actual = <Quantity -3.99680289e-15 rad>, desired = <Quantity 6.2781633e-15 rad>, rtol = 1e-07, atol = <Quantity 1.e-14 rad>, kwargs = {}
np = <module 'numpy' from '/home/yash/poli_astro/poli/lib/python3.8/site-packages/numpy/__init__.py'>
_unquantify_allclose_arguments = <function _unquantify_allclose_arguments at 0x7f9a4d2caaf0>

    def assert_quantity_allclose(actual, desired, rtol=1.e-7, atol=None,
                                 **kwargs):
        """
        Raise an assertion if two objects are not equal up to desired tolerance.
    
        This is a :class:`~astropy.units.Quantity`-aware version of
        :func:`numpy.testing.assert_allclose`.
        """
        import numpy as np
        from astropy.units.quantity import _unquantify_allclose_arguments
>       np.testing.assert_allclose(*_unquantify_allclose_arguments(
            actual, desired, rtol, atol), **kwargs)
E       AssertionError: 
E       Not equal to tolerance rtol=1e-07, atol=1e-14
E       
E       Mismatched elements: 1 / 1 (100%)
E       Max absolute difference: 1.02749662e-14
E       Max relative difference: 1.63661977
E        x: array(-3.996803e-15)
E        y: array(6.278163e-15)

../poli/lib/python3.8/site-packages/astropy/tests/helper.py:491: AssertionError
----------------------------------------------------------------------------- Hypothesis -----------------------------------------------------------------------------
Falsifying example: test_sample_closed_starts_and_ends_at_min_anomaly_if_in_range_and_no_max_given(
    min_nu=<Quantity 6.2781633e-15 rad>, ecc=<Quantity 0.99161489>,
)
```

**Ouput of `pip freeze`:**

<details>
  
```bash
alabaster==0.7.12
anyio==2.0.2
apipkg==1.5
appdirs==1.4.4
argon2-cffi==20.1.0
astroid==2.4.2
astropy==4.2
astropy-sphinx-theme==1.1
astroquery==0.4.1
async-generator==1.10
attrs==20.3.0
Babel==2.9.0
backcall==0.2.0
beautifulsoup4==4.9.3
black==20.8b1
bleach==3.2.1
certifi==2020.12.5
cffi==1.14.4
chardet==4.0.0
click==7.1.2
cognitive-complexity==1.2.0
colorama==0.4.4
confuse==1.4.0
coverage==5.3.1
cryptography==3.3.1
cycler==0.10.0
czml3==0.5.4
decorator==4.4.2
defusedxml==0.6.0
distlib==0.3.1
docutils==0.16
entrypoints==0.3
execnet==1.8.0
filelock==3.0.12
flake8==3.8.4
flake8-cognitive-complexity==0.1.0
flake8-polyfill==1.0.2
flit==3.0.0
flit-core==3.0.0
future==0.18.2
html5lib==1.1
htmlmin==0.1.12
hypothesis==6.0.1
idna==2.10
ImageHash==4.2.0
imagesize==1.2.0
iniconfig==1.1.1
ipykernel==5.4.3
ipython==7.19.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
isort==5.7.0
jedi==0.18.0
jeepney==0.6.0
Jinja2==2.11.2
joblib==1.0.0
jplephem==2.15
json5==0.9.5
jsonschema==3.2.0
jupyter-client==6.1.11
jupyter-core==4.7.0
jupyter-server==1.2.1
jupyterlab==3.0.4
jupyterlab-pygments==0.1.2
jupyterlab-server==2.1.2
jupyterlab-widgets==1.0.0
jupytext==1.9.1
keyring==21.8.0
kiwisolver==1.3.1
lazy-object-proxy==1.4.3
llvmlite==0.35.0
mando==0.6.4
markdown-it-py==0.6.1
MarkupSafe==1.1.1
matplotlib==3.3.3
mccabe==0.6.1
mdit-py-plugins==0.2.4
missingno==0.4.2
mistune==0.8.4
mypy==0.790
mypy-extensions==0.4.3
myst-parser==0.13.3
nbclassic==0.2.6
nbclient==0.5.1
nbconvert==6.0.7
nbformat==5.0.8
nbsphinx==0.8.0
nest-asyncio==1.4.3
networkx==2.5
nodejs==0.1.1
notebook==6.1.6
NotFound==1.0.2
npm==0.1.1
numba==0.52.0
numpy==1.20.0
numpydoc==1.1.0
optional-django==0.1.0
packaging==20.8
pandas==1.2.0
pandoc==1.0.2
pandocfilters==1.4.3
parso==0.8.1
pathspec==0.8.1
patsy==0.5.1
pexpect==4.8.0
phik==0.11.0
pickleshare==0.7.5
Pillow==8.1.0
plotly==4.14.3
plotly-express==0.4.1
pluggy==0.13.1
ply==3.11
poliastro==0.15.dev0
prometheus-client==0.9.0
prompt-toolkit==3.0.10
ptyprocess==0.7.0
py==1.10.0
pycodestyle==2.6.0
pycparser==2.20
pyerfa==1.7.1.1
pyflakes==2.2.0
Pygments==2.7.4
pyparsing==2.4.7
pyrsistent==0.17.3
pytest==6.2.2
pytest-cov==2.5.1
pytest-doctestplus==0.9.0
pytest-mpl==0.12
pytest-mypy==0.8.0
pytest-remotedata==0.3.2
python-dateutil==2.8.1
pytoml==0.1.21
pytz==2020.5
PyWavelets==1.1.1
PyYAML==5.3.1
pyzmq==20.0.0
radon==4.3.2
regex==2020.11.13
requests==2.25.1
retrying==1.3.3
scipy==1.6.0
seaborn==0.11.1
SecretStorage==3.3.0
Send2Trash==1.5.0
six==1.15.0
sniffio==1.2.0
snowballstemmer==2.0.0
sortedcontainers==2.3.0
soupsieve==2.1
Sphinx==3.4.3
sphinx-astropy==1.3
sphinx-autoapi==1.5.1
sphinx-automodapi==0.13
sphinx-gallery==0.8.2
sphinx-hoverxref==0.5b1
sphinx-notfound-page==0.6
sphinx-rtd-theme==0.5.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
statsmodels==0.12.1
tangled-up-in-unicode==0.0.6
Tcl==0.2
terminado==0.9.2
testpath==0.4.4
toml==0.10.2
tornado==6.1
tox==3.21.1
tqdm==4.56.0
traitlets==5.0.5
typed-ast==1.4.2
typing-extensions==3.7.4.3
Unidecode==1.1.2
urllib3==1.26.2
virtualenv==20.3.1
visions==0.6.0
w3lib==1.22.0
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.1
wrapt==1.12.1
```
```


```
</details>

📋  **Steps to solve the problem**
Investigate tests, specifically focusing on what eccentricities are being used to test them.

**Notes**
- The error traceback clearly states that we use falsifying examples for testing. Specifically, the problem seems to be in the eccentricity used: `0.99161489` (giving `-3.996803e-15` as the final true anomaly) where instead it must have used `0.88680956` which would have yielded a correct final true anomaly (`6.278163e-15`). See the test [here](https://github.com/poliastro/poliastro/blob/main/tests/tests_twobody/test_sampling.py#L62)
- This mostly seems to be a problem in the testing part of the code and not in the source code implementation.
- I am currently investigating the cause and am not sure if this is only me or if it is really a bug.

Please let me know if this is really a problem.

Thanks!!

**Comment by jorgepiloto** [comment] 2021-03-28 21:05
Hi @Yash-10, I tested locally and was not able to get any kind of error, all unit tests were passing... The CI do not show any error neither. Could you please try to update your local repository to main one and check if this still happens to you?

**Comment by astrojuanlu** [comment] 2021-04-03 17:05
Note that hypothesis tests a random combination of parameters every time, intelligently using this combination. And if it finds 1 combination that makes the test fail, it will save it to reproduce in the future. So, this test failure that you reported my be legitimate, but you will need to add it as an `example`: https://hypothesis.readthedocs.io/en/latest/reproducing.html?highlight=example#hypothesis.example

**Comment by Yash-10** [comment] 2021-04-04 03:59
Thanks @astrojuanlu adding it as an `@example` does solve the error. Although I was able to resolve the error by adding it as an example earlier, I was not sure if this error had some bigger implications.

So the learning is that: If we get an `AssertionError` for hypothesis due to a falsifying example, add it as an example so that `hypothesis` would not go on to check other examples not listed in your examples.

Now it seems to be resolved, thanks again for pointing out!

I would close this issue now....

**Comment by astrojuanlu** [comment] 2021-04-04 06:20
So, adding it as example fixed it? That's... Not what I expected 🤔 I thought that it would keep failing until we addressed it. Will try it locally in case I can reproduce it.

**Comment by Yash-10** [comment] 2021-04-05 20:04
Sorry for late reply @astrojuanlu I was too fast to come to a conclusion. Adding `@example` still gives the error, as expected, it had solved the error by adding a slightly different set of combinations as an `example`, not the one that currently gives the error.

**Some preliminary analysis:**
- Changing the `atol` argument solves the error locally:
```diff
+ assert_quantity_allclose(result[0], min_nu, atol=1.2e-14 * u.rad)
+ assert_quantity_allclose(result[-1], min_nu, atol=1.2e-14 * u.rad)
```
```diff
- assert_quantity_allclose(result[0], min_nu, atol=1e-14 * u.rad)
- assert_quantity_allclose(result[-1], min_nu, atol=1e-14 * u.rad)
```
but there probably needs to be a better fix for this. But since `hypothesis` uses random combinations of parameters, it might make sense to just change the `atol` argument in such cases because this doesn't signify issues with implementation accuracies but rather setting an unrealistic `atol`.

I tried to plot the absolute differences of `result[0]` and `result[-1]` which theoretically must be the same and practically under the limit set by `atol`.

1. **For ecc = 0.88680956:**

![Screenshot from 2021-04-06 01-23-10](https://user-images.githubusercontent.com/68844397/113619627-d80d7500-9676-11eb-96f0-989fbe80597b.png)

The values inside the list are the absolute differences, and the graph just plots them. As expected, all are below `1e-14`.

2. **For ecc = 0.99161489**

![Screenshot from 2021-04-06 01-26-30](https://user-images.githubusercontent.com/68844397/113619866-26bb0f00-9677-11eb-9ca1-ffe0bb178fbc.png)

As can be seen, `min_nu`'s between `6e-15` and `7e-15` shoot the difference above `1e-14`,

Hopefully not an overkill, but a plausible fix could be to set an `atol` value slightly higher than the highest difference we get by plotting such graphs because even `1.2e-14` could fail for some situations. Moreover, this process needs to be repeated for many eccentricities to be sure that this error doesn't occur anymore.

I had seen this error come up during some CI routines too.

What do you think @astrojuanlu ? Please correct me if I am not interpreting anything appropriately.

Thanks!

**Comment by Yash-10** [comment] 2021-04-06 13:51
As can be seen from the merging of a recent PR, such unrelated sampling errors do occur sometimes. For example, see [here](https://dev.azure.com/poliastro/c2409219-95a2-4e20-b99c-187990571f10/_apis/build/builds/934/logs/123).

This issue probably needs some investigation.

@astrojuanlu Does the above analysis support the process of fixing such errors. If not, I will dive deep into understanding `hypothesis` and try to find a solution for this issue :)

**Comment by astrojuanlu** [comment] 2021-04-06 16:10
@Yash-10 it's great analysis indeed! I think we have enough information at least to start. Perhaps, as you say, having a slightly larger `atol` is enough. But the plots are greatly appreciated anyway 😍

**Comment by Yash-10** [comment] 2021-04-07 15:46
Hello @astrojuanlu I have further analyzed the problem:

The mismatch between `min_nu` before and after sampling the orbit seems to increase rapidly as the eccentricity of the orbit reaches closer to 1. To confirm this, I tried to plot the variation of the absolute difference of the `min_nu`'s.

![Screenshot from 2021-04-07 20-57-35](https://user-images.githubusercontent.com/68844397/113892721-ecbb4b80-97e3-11eb-8551-554b1a9131be.png)

The eccentricities used are: `[0.5, 0.8, 0.9, 0.99, 0.999, 0.9999]`. As seen, the difference has already shooted `4e-14`. As one would expect, as eccentricity becomes exactly 1 (`ecc=1` => parabolic orbit), we would get a division by zero error.

Taking the eccentricity to the maximum possible value (as per the limitations of numerical precision: `ecc=0.9999999999999999`), the difference reaches `3.287386274308801e-08` which is `~1e7` times the expected difference.

**As a result, it seems that just changing `atol` is not a good choice**. I noticed some issues that deal with a related concept: for example in #908, there's already a lot of discussion done, although I would have to take a closer look to understand the details presented there.

Well, now it could be a non-trivial problem and the corresponding fix more involved.

**Comment by astrojuanlu** [comment] 2021-04-07 16:05
Oh wow, near-parabolic orbits there we go again... 😱 

This is an excellent investigation, thanks for taking the time to dig into this. I'm so happy that we are using hypothesis to surface these sort of problems. Will give this some thought over the weekend, if anyone has more ideas feel free to share here.

**Comment by Yash-10** [comment] 2021-04-10 13:38
I was looking at this note: https://arc.aiaa.org/doi/10.2514/3.49468, although I am skeptical of the relevance here, but there's a line which says:

> For near parabolic orbit, E and H are small and a direct computation is sensitive to error.

**Plot**

Eccentricities used: `[0.3, 0.5, 0.8, 0.9, 0.99, 0.999, 0.9999, 0.999999, 0.99999999, 0.999999999]`
![Screenshot from 2021-04-10 18-41-55](https://user-images.githubusercontent.com/68844397/114270922-92f99200-9a2c-11eb-80ed-1feb32f6f510.png)


From this, what I started to think is that the errors might be because of the way eccentric anomaly (E) is calculated currently i.e. using the half-angle formula. From the formula:

![Screenshot from 2021-04-10 18-45-00](https://user-images.githubusercontent.com/68844397/114270995-e66be000-9a2c-11eb-95c4-da8eddd54302.png)

- If the true anomaly is 0, then the eccentric anomaly is exactly 0 <sup>1</sup>, irrespective of the closeness of ecc to 1. As a result, getting sampling errors for orbits with `nu = 0 * u.rad` is mostly not going to be a problem. 
- Moreover, the problem could be in cases where:

    1. The true anomaly (`nu`) is close to zero.
    2. The eccentricity (`e`) is close to 1.

because each of them will contribute in making the eccentric anomaly close to zero.

If both 1 and 2 are satisfied, then it's highly likely to get errors in sampling. This can be verified from the falsifying example while testing that started this discussion:

```
min_nu=<Quantity 6.2781633e-15 rad>, ecc=<Quantity 0.99161489>
```
Here, `min_nu` is very close to 0 and `ecc` is very close to 1.

So, could this be a potential place to investigate @astrojuanlu ? Please correct me if I have interpreted something incorrectly.

Thanks!

**Footnotes**
1. Although `nu = 0` could imply the eccentric anomaly to be either `0` or `pi`, `np.arctan` returns values only in the range `[-pi/2, +pi/2]` => According to me, we will get `0` always and never `pi`. 

Would it be better to use `np.arctan2` instead of `np.arctan` since `np.arctan2` returns values in the range `[-pi, +pi]` whereas `np.arctan` doesn't?

**Comment by Yash-10** [comment] 2021-04-12 14:38
I noticed some related logic that was probably introduced in #908 ([here](https://github.com/poliastro/poliastro/blob/main/src/poliastro/core/propagation/farnocchia.py#L247-L251)) where the mean anomaly is recalculated if the orbit is near-parabolic and then `nu` is calculated. So I would need to take a look at the discussion there, to understand why this was done. Looks interesting!

```py
# Near parabolic, recompute M
n = np.sqrt(k / (2 * q ** 3))
M = n * delta_t
D = M_to_D_near_parabolic(M, ecc)
nu = D_to_nu(D)
```
@astrojuanlu Could you let me know your thoughts on the above analysis?

Thanks!

**Comment by astrojuanlu** [comment] 2021-04-12 14:49
> I was looking at this note: https://arc.aiaa.org/doi/10.2514/3.49468

Nice! I didn't know about this paper.

Our treatment of near-parabolic orbits is based on Farnocchia et al "Robust resolution of Kepler’s equation in all eccentricity regimes" https://doi.org/10.1007/s10569-013-9476-9 . If you want to understand what's happening there, it's very important that you read that paper carefully. After a lot of effort we managed to get this right in #908 and its follow-ups (thanks to the pandemic!)

**Comment by astrojuanlu** [comment] 2021-04-12 14:50
Bear in mind that the dangerous combination is `ecc -> 1` and `E -> pi`, because `ecc = 1` and `E = pi` is mathematically impossible.

**Comment by Yash-10** [comment] 2021-04-12 15:27
> Our treatment of near-parabolic orbits is based on Farnocchia et al "Robust resolution of Kepler’s equation in all eccentricity regimes" https://doi.org/10.1007/s10569-013-9476-9 . If you want to understand what's happening there, it's very important that you read that paper carefully

Thank you so much @astrojuanlu I will surely read that paper. 

> After a lot of effort we managed to get this right in #908 and its follow-ups (thanks to the pandemic!)

Yes, it was indeed a long PR and great effort!!

> Bear in mind that the dangerous combination is ecc -> 1 and E -> pi, because ecc = 1 and E = pi is mathematically impossible.

Thanks, I will keep that in mind. It was interesting to see the heavy dependence of `E` on `ecc` in near-parabolic regions!

**Comment by astrojuanlu** [comment] 2021-07-16 09:41
We are wondering if this can be related to #1276 somehow, although it seems unlikely

**Comment by astrojuanlu** [comment] 2022-06-08 10:39
@Yash-10 is this test still failing for you? I noticed a [`@reproduce_failure`](https://hypothesis.readthedocs.io/en/latest/reproducing.html#reproducing-an-example-with-reproduce-failure) decorator we could try to use. If configured correctly, it will output information like this:

```
You can reproduce this example by temporarily adding @reproduce_failure(..., b'AAAA//AAAAAAAAEA') as a decorator on your test case
```

There have been some changes in NumPy and numba during this last year, so maybe it's worth trying again in a new installation.

On the other hand, now that I know that numba and numpy might get slightly different numerical results depending on the CPU architecture, it's worth adding the output of `numba -s` for your computer.

**Comment by Yash-10** [comment] 2022-06-08 18:41
Ok, I tried running the tests again, and now I do not get any errors!

**Comment by astrojuanlu** [comment] 2022-06-08 19:57
Marvelous! Closing

**Closed by astrojuanlu** 2022-06-08 19:57 UTC
Labels: bug, needs more info
