### ISSUE TITLE
Orbital state, longitude and latitude

### ISSUE THREAD

**Issue by cSchubes** [poliastro/poliastro#442] opened 2018-09-04 14:06 UTC
🐞 The state is completely hidden from the user, so I have no idea what it entails. What I need is to be able to propagate the orbit, and obtain the longitude and latitude of the satellite over the surface of the Earth at any given time in the orbit.

🖥 
`python -c "import poliastro.testing; poliastro.testing.test()"`

`pip freeze | grep astropy`

`pip freeze | grep poliastro`

🎯 This is important to me for my simulation work, especially since I don't know much about orbital dynamics (I'm an electrical engineer). Also, making the state clear in the docs would be super helpful.

💡 **Possible solutions**
Add state documentation and if possible, make the longitude/latitude available in that state.

📋  N/A

**Comment by cSchubes** [comment] 2018-09-04 14:09
sorry, forgot the outputs.

`pip freeze | grep astropy` :
astropy==3.0.4
`pip freeze | grep poliastro`:
poliastro==0.10.0

Tests are currently running.

**Comment by cSchubes** [comment] 2018-09-04 18:32
On this link: [http://docs.poliastro.space/en/latest/user_guide.html#defining-the-orbit-orbit-objects] in the 'From classical orbital elements' section it says 'To see a complete list of properties, check out the poliastro.twobody.orbit.Orbit class on the API reference.'

But when I follow that link to [http://docs.poliastro.space/en/latest/safe.html#poliastro.twobody.orbit.Orbit](http://docs.poliastro.space/en/latest/safe.html#poliastro.twobody.orbit.Orbit) there is not a list of what the state object contains.

**Comment by Juanlu001** [comment] 2018-09-04 18:44
This is a duplicate of https://github.com/poliastro/poliastro/issues/435 then - and I must admit I didn't remember that sentence in the user guide, it's misleading. I'm closing this one, feel free to comment further if you have more questions.

**Closed by Juanlu001** 2018-09-04 18:44 UTC
Labels: enhancement, question
